// Detects auto-generated venue contact emails so the inquiry path can divert
// them to a fallback flow instead of sending mail into the void.
//
// mockData.ts synthesizes an email for every venue using:
//   `info@${name.toLowerCase().replace(/\s+/g, '').replace(/[^a-z0-9]/g, '')}.com`
// Any email matching exactly that pattern for the same venue name is fake and
// will not deliver.

function slugifyVenueNameForEmail(venueName: string): string {
  return (venueName || 'venue')
    .toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9]/g, '');
}

export function isAutoGeneratedVenueEmail(email: string, venueName: string): boolean {
  if (!email || !venueName) return false;
  const expected = `info@${slugifyVenueNameForEmail(venueName)}.com`;
  return email.trim().toLowerCase() === expected;
}
