// Hero image URLs for high-impact landing pages. Generated by
// scripts/generate-page-photos.ts (DALL-E 3, 1792×1024 standard, vivid)
// and stored in the public Supabase `blog-images` bucket under `pages/`.
//
// Re-running the script with --dry-run prints the URLs again; the script
// is idempotent, so re-running it without --dry-run is a no-op when the
// files already exist in storage.

export const PAGE_HERO_IMAGES = {
  about: 'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/pages/about/hero.png',
  venues: 'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/pages/venues/hero.png',
  vendors: 'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/pages/vendors/hero.png',
  'dress-shops': 'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/pages/dress-shops/hero.png',
  blog: 'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/pages/blog/hero.png',
} as const;

export type PageHeroSlug = keyof typeof PAGE_HERO_IMAGES;
