// Watercolor placeholder URLs for venue + dress-shop cards.
//
// Generated by scripts/generate-watercolor-placeholders-batch.ts (DALL-E 3,
// 1024×1024 standard, vivid) and stored in the public Supabase blog-images
// bucket under `placeholders/venues/<slug>.png` and
// `placeholders/dress-shops/<slug>.png`.
//
// Slug source: the venues.slug / dress_shops.slug column. Storage filenames
// match the DB column 1:1 (verified by listing the storage bucket and
// cross-referencing both tables — 129/129 venues, 31/31 dress shops).
//
// These helpers don't gate on existence — they always return a URL. Cards
// should pair them with an onError handler so a missing PNG doesn't break
// the card render.

const SUPABASE_PUBLIC_BASE =
  'https://aflrmpkolumpjhpaxblz.supabase.co/storage/v1/object/public/blog-images/placeholders';

export function placeholderUrlForVenue(slug: string): string {
  return `${SUPABASE_PUBLIC_BASE}/venues/${slug}.png`;
}

export function placeholderUrlForDressShop(slug: string): string {
  return `${SUPABASE_PUBLIC_BASE}/dress-shops/${slug}.png`;
}

export function placeholderUrlForVendor(slug: string): string {
  return `${SUPABASE_PUBLIC_BASE}/vendors/${slug}.png`;
}
