import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';
import { supabase } from '../../../lib/supabase';
import { isAutoGeneratedVenueEmail } from '../../../lib/inquiryValidation';

const resend = new Resend(process.env.RESEND_API_KEY);

// Where leads land when the venue's listed email is auto-generated and would
// otherwise bounce. Configurable so the user can rotate without a deploy.
const FALLBACK_LEAD_EMAIL =
  process.env.LEAD_FALLBACK_EMAIL || 'hello@floridaweddingwonders.com';

type LeadStatus = 'sent' | 'pending-real-email' | 'failed';

export async function POST(request: NextRequest) {
  try {
    const leadData = await request.json();

    const {
      venueId,
      venueName,
      venueEmail,
      userName,
      userEmail,
      message,
      leadQualification,
      submittedAt,
    } = leadData;

    if (!venueName || !venueEmail || !userName || !userEmail || !message) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      );
    }

    const venueEmailReal = !isAutoGeneratedVenueEmail(venueEmail, venueName);
    let status: LeadStatus = venueEmailReal ? 'sent' : 'pending-real-email';
    let resendVenueId: string | null = null;
    let resendUserId: string | null = null;
    let resendError: string | null = null;

    // 1) Persist the lead first. Best-effort: if the venue_leads table has not
    //    been migrated yet we log and continue — the email path below still
    //    runs so a stale schema does not silently drop the user's submission.
    const persistedLeadId = await persistLead({
      venueId,
      venueName,
      venueEmail,
      venueEmailReal,
      userName,
      userEmail,
      userPhone: leadQualification?.phoneNumber || null,
      message,
      qualification: leadQualification || null,
      status,
      submittedAt,
    });

    // 2) Notify whichever inbox is responsible. Real venue email → venue.
    //    Auto-generated → central fallback inbox so we can manually relay.
    const venueRecipient = venueEmailReal ? venueEmail : FALLBACK_LEAD_EMAIL;
    const venueSubjectPrefix = venueEmailReal
      ? '🎉 New Wedding Inquiry'
      : '⚠️ New Wedding Inquiry — venue email needs attention';

    try {
      const venueResult = await resend.emails.send({
        from: 'Florida Wedding Wonders <noreply@floridaweddingwonders.com>',
        to: [venueRecipient],
        subject: `${venueSubjectPrefix} — ${
          leadQualification?.eventType || 'Wedding'
        } for ${leadQualification?.guestCount || 'TBD'} guests at ${venueName}`,
        html: generateVenueLeadEmail({ ...leadData, venueEmailReal }),
        text: generateVenueLeadTextEmail({ ...leadData, venueEmailReal }),
      });
      resendVenueId =
        (venueResult as any)?.data?.id || (venueResult as any)?.id || null;
    } catch (err) {
      resendError = err instanceof Error ? err.message : String(err);
      status = 'failed';
      console.error('Venue notification email failed:', err);
    }

    // 3) Confirmation to the user — same in both paths, copy is honest about
    //    the next step rather than claiming the venue already has the message.
    try {
      const userResult = await resend.emails.send({
        from: 'Florida Wedding Wonders <noreply@floridaweddingwonders.com>',
        to: [userEmail],
        subject: `✅ We've received your inquiry for ${venueName}`,
        html: generateUserConfirmationEmail({ ...leadData, venueEmailReal }),
        text: generateUserConfirmationTextEmail({ ...leadData, venueEmailReal }),
      });
      resendUserId =
        (userResult as any)?.data?.id || (userResult as any)?.id || null;
    } catch (err) {
      console.error('User confirmation email failed:', err);
      // Don't downgrade status here — the lead is captured and the venue side
      // is what actually matters for the bleed-stop.
    }

    // 4) Annotate the persisted lead with Resend ids / status. Best-effort.
    if (persistedLeadId && (resendVenueId || resendUserId || resendError)) {
      await annotateLead(persistedLeadId, {
        status,
        resendVenueId,
        resendUserId,
        resendError,
      });
    }

    return NextResponse.json({
      success: true,
      status,
      message:
        status === 'pending-real-email'
          ? "We've received your inquiry and our team will reach out within 24-48 hours."
          : 'Lead sent successfully to venue',
    });
  } catch (error) {
    console.error('Failed to process venue lead:', error);
    return NextResponse.json(
      {
        success: false,
        error:
          'Internal server error: ' +
          (error instanceof Error ? error.message : 'Unknown error'),
      },
      { status: 500 }
    );
  }
}

async function persistLead(input: {
  venueId: string | undefined;
  venueName: string;
  venueEmail: string;
  venueEmailReal: boolean;
  userName: string;
  userEmail: string;
  userPhone: string | null;
  message: string;
  qualification: unknown;
  status: LeadStatus;
  submittedAt: string | undefined;
}): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from('venue_leads')
      .insert({
        venue_id: input.venueId || 'unknown',
        venue_name: input.venueName,
        venue_email: input.venueEmail,
        venue_email_real: input.venueEmailReal,
        user_name: input.userName,
        user_email: input.userEmail,
        user_phone: input.userPhone,
        message: input.message,
        qualification: input.qualification,
        status: input.status,
        submitted_at: input.submittedAt || new Date().toISOString(),
      })
      .select('id')
      .single();

    if (error) {
      // PGRST205 = "Could not find the table" — migration not applied yet.
      // Anything else is also non-fatal; we log and continue.
      console.warn('venue_leads insert skipped:', error.code, error.message);
      return null;
    }
    return data?.id || null;
  } catch (err) {
    console.warn('venue_leads insert threw:', err);
    return null;
  }
}

async function annotateLead(
  leadId: string,
  patch: {
    status: LeadStatus;
    resendVenueId: string | null;
    resendUserId: string | null;
    resendError: string | null;
  }
): Promise<void> {
  try {
    await supabase
      .from('venue_leads')
      .update({
        status: patch.status,
        resend_venue_id: patch.resendVenueId,
        resend_user_id: patch.resendUserId,
        resend_error: patch.resendError,
      })
      .eq('id', leadId);
  } catch (err) {
    console.warn('venue_leads annotate skipped:', err);
  }
}

function generateVenueLeadEmail(leadData: any): string {
  const { leadQualification, venueEmailReal } = leadData;

  const fallbackBanner = venueEmailReal
    ? ''
    : `
      <div style="background: #fef3c7; border-left: 4px solid #f59e0b; padding: 16px; margin: 0 0 20px 0; border-radius: 8px;">
        <strong style="color: #92400e;">Heads up:</strong>
        <span style="color: #92400e;">
          The listing for ${escapeHtml(leadData.venueName)} does not yet have a verified email on file —
          this inquiry was routed to the central inbox. Please forward to the venue manually
          and update the listing with their real contact address.
        </span>
      </div>`;

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%); padding: 20px;">
      <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.1);">
        ${fallbackBanner}
        <div style="text-align: center; margin-bottom: 30px;">
          <div style="width: 80px; height: 80px; background: linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%); border-radius: 16px; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;">
            <span style="color: white; font-size: 32px;">💕</span>
          </div>
          <h1 style="color: #ec4899; margin: 0; font-size: 28px;">New Wedding Inquiry!</h1>
          <p style="color: #64748b; font-size: 18px; margin: 10px 0;">A qualified lead is interested in ${escapeHtml(
            leadData.venueName
          )}</p>
        </div>

        <div style="background: #fef7ff; border-left: 4px solid #ec4899; padding: 20px; margin: 20px 0; border-radius: 8px;">
          <h2 style="color: #ec4899; margin: 0 0 15px 0;">Contact Information:</h2>
          <p style="margin: 8px 0; font-size: 16px;"><strong>Name:</strong> ${escapeHtml(
            leadData.userName
          )}</p>
          <p style="margin: 8px 0; font-size: 16px;"><strong>Email:</strong> ${escapeHtml(
            leadData.userEmail
          )}</p>
          ${
            leadQualification?.phoneNumber
              ? `<p style="margin: 8px 0; font-size: 16px;"><strong>Phone:</strong> ${escapeHtml(
                  leadQualification.phoneNumber
                )}</p>`
              : ''
          }
          <p style="margin: 8px 0; font-size: 16px;"><strong>Inquiry Date:</strong> ${new Date(
            leadData.submittedAt
          ).toLocaleDateString()}</p>
        </div>

        ${
          leadQualification
            ? `
          <div style="background: #f0f9ff; border-left: 4px solid #0ea5e9; padding: 20px; margin: 20px 0; border-radius: 8px;">
            <h2 style="color: #0ea5e9; margin: 0 0 15px 0;">🎯 Pre-Qualified Wedding Details:</h2>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Event Type:</strong> ${escapeHtml(
              leadQualification.eventType
            )}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Guest Count:</strong> ${escapeHtml(
              String(leadQualification.guestCount)
            )} guests</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Venue Budget:</strong> ${escapeHtml(
              leadQualification.venuebudget
            )}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Date Flexibility:</strong> ${escapeHtml(
              leadQualification.dateFlexibility
            )}</p>
            ${
              leadQualification.preferredDate
                ? `<p style="margin: 8px 0; font-size: 16px;"><strong>Preferred Date:</strong> ${new Date(
                    leadQualification.preferredDate
                  ).toLocaleDateString()}</p>`
                : ''
            }
          </div>
        `
            : `
          <div style="background: #fef3c7; border-left: 4px solid #f59e0b; padding: 20px; margin: 20px 0; border-radius: 8px;">
            <h3 style="color: #f59e0b; margin: 0 0 15px 0;">⚠️ Note:</h3>
            <p style="color: #92400e;">This user hasn't completed their wedding profile yet. You may want to ask for guest count, budget, and date preferences.</p>
          </div>
        `
        }

        <div style="background: #f0fdf4; border-left: 4px solid #10b981; padding: 20px; margin: 20px 0; border-radius: 8px;">
          <h3 style="color: #10b981; margin: 0 0 15px 0;">💬 Their Message:</h3>
          <p style="color: #334155; line-height: 1.6; font-style: italic; background: white; padding: 15px; border-radius: 8px; margin: 0;">"${escapeHtml(
            leadData.message
          )}"</p>
        </div>

        <div style="text-align: center; margin: 30px 0;">
          <a href="mailto:${encodeURI(
            leadData.userEmail
          )}" style="background: linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%); color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: bold; margin-right: 10px;">Reply to Lead</a>
          ${
            leadQualification?.phoneNumber
              ? `<a href="tel:${encodeURI(
                  leadQualification.phoneNumber
                )}" style="background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: bold;">Call Now</a>`
              : ''
          }
        </div>
      </div>
    </div>
  `;
}

function generateVenueLeadTextEmail(leadData: any): string {
  const { leadQualification, venueEmailReal } = leadData;
  const banner = venueEmailReal
    ? ''
    : `[Heads up: ${leadData.venueName} does not yet have a verified email on file. This inquiry was routed to the central inbox — please forward to the venue manually.]\n\n`;

  return `${banner}New Wedding Inquiry — ${leadData.venueName}

Contact Information:
- Name: ${leadData.userName}
- Email: ${leadData.userEmail}
${leadQualification?.phoneNumber ? `- Phone: ${leadQualification.phoneNumber}` : ''}
- Inquiry Date: ${new Date(leadData.submittedAt).toLocaleDateString()}

${
  leadQualification
    ? `Wedding Details:
- Event Type: ${leadQualification.eventType}
- Guest Count: ${leadQualification.guestCount} guests
- Venue Budget: ${leadQualification.venuebudget}
- Date Flexibility: ${leadQualification.dateFlexibility}
${
  leadQualification.preferredDate
    ? `- Preferred Date: ${new Date(leadQualification.preferredDate).toLocaleDateString()}`
    : ''
}`
    : "Note: This user hasn't completed their wedding profile yet."
}

Their Message:
"${leadData.message}"

Reply to: ${leadData.userEmail}
${leadQualification?.phoneNumber ? `Call: ${leadQualification.phoneNumber}` : ''}

Florida Wedding Wonders — Lead Generation System`;
}

function generateUserConfirmationEmail(leadData: any): string {
  const { venueEmailReal } = leadData;
  const responseLine = venueEmailReal
    ? `Your detailed inquiry has been delivered to ${escapeHtml(leadData.venueName)}. Expect a response within 24-48 hours.`
    : `We've captured your inquiry for ${escapeHtml(
        leadData.venueName
      )}. Our team is finalizing the venue's contact details and will reach out within 24-48 hours.`;

  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: linear-gradient(135deg, #10b981 0%, #059669 100%); padding: 20px;">
      <div style="background: white; border-radius: 12px; padding: 30px; box-shadow: 0 10px 25px rgba(0,0,0,0.1);">
        <div style="text-align: center; margin-bottom: 30px;">
          <div style="width: 80px; height: 80px; background: linear-gradient(135deg, #10b981 0%, #059669 100%); border-radius: 16px; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center;">
            <span style="color: white; font-size: 32px;">✅</span>
          </div>
          <h1 style="color: #10b981; margin: 0; font-size: 28px;">Inquiry Received!</h1>
          <p style="color: #64748b; font-size: 18px; margin: 10px 0;">${responseLine}</p>
        </div>

        <div style="background: #f0fdf4; border: 2px solid #10b981; padding: 25px; margin: 25px 0; border-radius: 12px; text-align: center;">
          <h2 style="color: #10b981; margin: 0 0 15px 0;">🏛️ ${escapeHtml(leadData.venueName)}</h2>
          <p style="color: #334155; font-size: 16px; margin: 0;">Your wedding details are on their way.</p>
        </div>

        <div style="background: #eff6ff; border: 1px solid #3b82f6; padding: 20px; margin: 25px 0; border-radius: 8px;">
          <h3 style="color: #3b82f6; margin: 0 0 15px 0;">📞 What Happens Next?</h3>
          <ol style="color: #334155; line-height: 1.8; margin: 0; padding-left: 20px;">
            <li>${
              venueEmailReal
                ? 'The venue receives your full inquiry with budget and date preferences.'
                : 'Our team verifies the venue contact and forwards your inquiry directly.'
            }</li>
            <li>Expect a response within 24-48 hours via email or phone.</li>
            <li>They may offer a tour, share availability, or quote pricing for your guest count.</li>
          </ol>
        </div>

        <div style="text-align: center; margin: 30px 0;">
          <p style="color: #64748b; margin-bottom: 15px;">Need help in the meantime?</p>
          <a href="mailto:hello@floridaweddingwonders.com" style="background: linear-gradient(135deg, #ec4899 0%, #8b5cf6 100%); color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block; font-weight: bold;">Contact Support</a>
        </div>
      </div>
    </div>
  `;
}

function generateUserConfirmationTextEmail(leadData: any): string {
  const { venueEmailReal } = leadData;
  return `Inquiry Received!

${
  venueEmailReal
    ? `Your detailed inquiry has been delivered to ${leadData.venueName}.`
    : `We've captured your inquiry for ${leadData.venueName}. Our team is finalizing the venue's contact details and will reach out shortly.`
}

What happens next:
1. ${
    venueEmailReal
      ? 'The venue receives your full inquiry with budget and date preferences.'
      : 'Our team verifies the venue contact and forwards your inquiry directly.'
  }
2. Expect a response within 24-48 hours via email or phone.
3. They may offer a tour, share availability, or quote pricing.

Questions? Contact hello@floridaweddingwonders.com

Florida Wedding Wonders — Connecting Couples with Perfect Venues`;
}

// Minimal HTML escape so user-provided strings can't break out of the email
// template. Resend's HTML pipeline does not sanitize for us.
function escapeHtml(value: string): string {
  if (value == null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
