import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { Resend } from 'resend';
import { randomUUID } from 'crypto';
import { supabase } from '@/lib/supabase';
import { createSupabaseAdminClient } from '@/lib/supabaseServer';
import { getAppSession } from '@/lib/authServer';
import { isAutoGeneratedVenueEmail } from '@/lib/inquiryValidation';

// POST /api/multi-quote
//
// Accepts a multi-quote submission targeting up to 5 venues. Each venue
// becomes its own row in venue_leads sharing a single multi_quote_id, so
// owners can see "you're 1 of 5 — respond fast" and analytics can rank
// these as higher-intent than single-venue inquiries.
//
// The venue's listed email gets a "Multi-Quote" notification that explicitly
// says they're competing. The user gets one consolidated confirmation.

const resend = new Resend(process.env.RESEND_API_KEY);
const FALLBACK_LEAD_EMAIL =
  process.env.LEAD_FALLBACK_EMAIL || 'hello@floridaweddingwonders.com';

const VenueTarget = z.object({
  venueId: z.string().min(1),
  venueName: z.string().min(1),
  venueEmail: z.string().email(),
});

const Body = z.object({
  userName: z.string().min(1).max(120),
  userEmail: z.string().email(),
  message: z.string().min(10).max(4000),
  leadQualification: z.object({
    eventType: z.string().optional().default('Wedding'),
    guestCount: z.number().int().nonnegative().max(10000),
    preferredDate: z.string().optional().nullable(),
    dateFlexibility: z.string().optional().nullable(),
    venuebudget: z.string().optional().nullable(),
    phoneNumber: z.string().optional().nullable(),
    fullName: z.string().optional().nullable(),
    email: z.string().optional().nullable(),
  }),
  venues: z.array(VenueTarget).min(2).max(5),
});

export async function POST(request: NextRequest) {
  let parsed: z.infer<typeof Body>;
  try {
    parsed = Body.parse(await request.json());
  } catch (err) {
    const message =
      err instanceof z.ZodError
        ? err.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')
        : 'Invalid body';
    return NextResponse.json({ success: false, error: message }, { status: 400 });
  }

  const submittedAt = new Date().toISOString();
  const multiQuoteId = randomUUID();

  // Sync the lead-qualification snapshot to the user's profile if signed in.
  const session = await getAppSession().catch(() => null);
  if (session?.user.id) {
    try {
      const admin = createSupabaseAdminClient();
      await admin
        .from('profiles')
        .update({
          phone: parsed.leadQualification.phoneNumber || undefined,
          wedding_date: parsed.leadQualification.preferredDate || undefined,
          guest_count:
            typeof parsed.leadQualification.guestCount === 'number'
              ? parsed.leadQualification.guestCount
              : undefined,
          preferences: parsed.leadQualification,
        })
        .eq('id', session.user.id);
    } catch (e) {
      console.warn('multi-quote profile sync skipped:', e);
    }
  }

  // Loop each target venue: persist lead row + email venue + email owner(s).
  const results: Array<{
    venueId: string;
    venueName: string;
    leadId: string | null;
    status: 'sent' | 'pending-real-email' | 'failed';
    error?: string;
  }> = [];

  for (const target of parsed.venues) {
    const venueEmailReal = !isAutoGeneratedVenueEmail(target.venueEmail, target.venueName);
    let status: 'sent' | 'pending-real-email' | 'failed' = venueEmailReal
      ? 'sent'
      : 'pending-real-email';
    let lastError: string | undefined;

    // 1) Persist the row
    let leadId: string | null = null;
    try {
      const { data, error } = await supabase
        .from('venue_leads')
        .insert({
          venue_id: target.venueId,
          venue_name: target.venueName,
          venue_email: target.venueEmail,
          venue_email_real: venueEmailReal,
          user_name: parsed.userName,
          user_email: parsed.userEmail,
          user_phone: parsed.leadQualification.phoneNumber || null,
          message: parsed.message,
          qualification: parsed.leadQualification,
          status,
          submitted_at: submittedAt,
          multi_quote_id: multiQuoteId,
        })
        .select('id')
        .single();
      if (error) {
        console.warn('multi-quote insert skipped:', error.code, error.message);
      } else {
        leadId = data?.id || null;
      }
    } catch (e) {
      console.warn('multi-quote insert threw:', e);
    }

    // 2) Email the venue's listed inbox (or fallback if auto-generated)
    const venueRecipient = venueEmailReal ? target.venueEmail : FALLBACK_LEAD_EMAIL;
    try {
      await resend.emails.send({
        from: 'Florida Wedding Wonders <noreply@floridaweddingwonders.com>',
        to: [venueRecipient],
        subject: venueEmailReal
          ? `🔥 Multi-Quote Inquiry — you're 1 of ${parsed.venues.length} — ${target.venueName}`
          : `⚠️ Multi-Quote Inquiry — venue email needs attention — ${target.venueName}`,
        html: renderMultiQuoteVenueEmail({
          venueName: target.venueName,
          venueEmailReal,
          userName: parsed.userName,
          userEmail: parsed.userEmail,
          message: parsed.message,
          qualification: parsed.leadQualification,
          peerCount: parsed.venues.length - 1,
        }),
      });
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err);
      status = 'failed';
      console.error('multi-quote venue email failed:', err);
    }

    // 3) Email the owner inbox(es) if claimed
    try {
      await notifyOwnersOfVenue({
        venueIdLegacyOrUuid: target.venueId,
        venueName: target.venueName,
        userName: parsed.userName,
        userEmail: parsed.userEmail,
        message: parsed.message,
        qualification: parsed.leadQualification,
        peerCount: parsed.venues.length - 1,
      });
    } catch (e) {
      console.warn('multi-quote owner email skipped:', e);
    }

    results.push({
      venueId: target.venueId,
      venueName: target.venueName,
      leadId,
      status,
      error: lastError,
    });
  }

  // 4) Single confirmation to the user covering all venues at once.
  try {
    await resend.emails.send({
      from: 'Florida Wedding Wonders <noreply@floridaweddingwonders.com>',
      to: [parsed.userEmail],
      subject: `✅ Quotes requested from ${parsed.venues.length} venues`,
      html: renderUserConfirmationEmail({
        userName: parsed.userName,
        venues: parsed.venues.map((v) => v.venueName),
        guestCount: parsed.leadQualification.guestCount,
      }),
    });
  } catch (err) {
    console.error('multi-quote user confirmation email failed:', err);
  }

  const failures = results.filter((r) => r.status === 'failed');
  return NextResponse.json({
    success: true,
    multiQuoteId,
    venueCount: parsed.venues.length,
    results,
    partialFailure: failures.length > 0,
  });
}

// ---------------------------------------------------------------------------
// Owner notification — same pattern as /api/venue-leads
// ---------------------------------------------------------------------------

async function notifyOwnersOfVenue(input: {
  venueIdLegacyOrUuid: string;
  venueName: string;
  userName: string;
  userEmail: string;
  message: string;
  qualification: any;
  peerCount: number;
}): Promise<void> {
  const admin = createSupabaseAdminClient();

  let venueUuid: string | null = null;
  if (
    /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
      input.venueIdLegacyOrUuid
    )
  ) {
    venueUuid = input.venueIdLegacyOrUuid;
  } else {
    const { data: vRow } = await admin
      .from('venues')
      .select('id')
      .eq('legacy_id', input.venueIdLegacyOrUuid)
      .maybeSingle();
    venueUuid = vRow?.id ?? null;
  }
  if (!venueUuid) return;

  const { data: ownerships } = await admin
    .from('venue_ownerships')
    .select('profile_id, profiles:profile_id(email, full_name)')
    .eq('venue_id', venueUuid)
    .eq('status', 'active');
  if (!ownerships || ownerships.length === 0) return;

  for (const row of ownerships as any[]) {
    const ownerEmail = row.profiles?.email;
    if (!ownerEmail) continue;
    try {
      await resend.emails.send({
        from: 'Florida Wedding Wonders <noreply@floridaweddingwonders.com>',
        to: [ownerEmail],
        subject: `🔥 Multi-Quote Inquiry for ${input.venueName} — competing with ${input.peerCount} other ${
          input.peerCount === 1 ? 'venue' : 'venues'
        }`,
        html: renderMultiQuoteVenueEmail({
          venueName: input.venueName,
          venueEmailReal: true,
          userName: input.userName,
          userEmail: input.userEmail,
          message: input.message,
          qualification: input.qualification,
          peerCount: input.peerCount,
        }),
      });
    } catch (e) {
      console.warn('owner email failed for', ownerEmail, e);
    }
  }
}

// ---------------------------------------------------------------------------
// Email templates
// ---------------------------------------------------------------------------

function renderMultiQuoteVenueEmail(args: {
  venueName: string;
  venueEmailReal: boolean;
  userName: string;
  userEmail: string;
  message: string;
  qualification: any;
  peerCount: number;
}): string {
  const q = args.qualification;
  const fallbackBanner = args.venueEmailReal
    ? ''
    : `<div style="background:#fef3c7;border-left:4px solid #f59e0b;padding:14px;margin:0 0 18px 0;border-radius:8px;color:#92400e;">
        <strong>Heads up:</strong> ${escapeHtml(args.venueName)} doesn't have a verified email on file — this inquiry routed to the central inbox.
      </div>`;

  return `<div style="font-family:Arial,sans-serif;max-width:620px;margin:0 auto;background:linear-gradient(135deg,#ec4899 0%,#8b5cf6 100%);padding:20px;">
    <div style="background:white;border-radius:12px;padding:30px;">
      ${fallbackBanner}
      <div style="background:#fef2f2;border:2px solid #f43f5e;padding:14px;border-radius:8px;text-align:center;margin-bottom:20px;">
        <strong style="color:#be123c;font-size:15px;">⚡ Multi-Quote Inquiry — you're 1 of ${
          args.peerCount + 1
        }. Respond fast to win the lead.</strong>
      </div>
      <h1 style="color:#ec4899;margin:0 0 4px 0;">New Wedding Inquiry</h1>
      <p style="color:#64748b;margin:0 0 20px 0;">Couple is considering ${escapeHtml(args.venueName)} alongside ${
    args.peerCount
  } other ${args.peerCount === 1 ? 'venue' : 'venues'}.</p>

      <div style="background:#fef7ff;border-left:4px solid #ec4899;padding:18px;border-radius:8px;margin:18px 0;">
        <h2 style="color:#ec4899;margin:0 0 10px 0;">Contact</h2>
        <p style="margin:6px 0;"><strong>Name:</strong> ${escapeHtml(args.userName)}</p>
        <p style="margin:6px 0;"><strong>Email:</strong> ${escapeHtml(args.userEmail)}</p>
        ${q.phoneNumber ? `<p style="margin:6px 0;"><strong>Phone:</strong> ${escapeHtml(q.phoneNumber)}</p>` : ''}
      </div>

      <div style="background:#f0f9ff;border-left:4px solid #0ea5e9;padding:18px;border-radius:8px;margin:18px 0;">
        <h2 style="color:#0ea5e9;margin:0 0 10px 0;">🎯 Wedding Details</h2>
        <p style="margin:6px 0;"><strong>Guest count:</strong> ${escapeHtml(String(q.guestCount))}</p>
        ${q.venuebudget ? `<p style="margin:6px 0;"><strong>Budget:</strong> ${escapeHtml(q.venuebudget)}</p>` : ''}
        ${q.dateFlexibility ? `<p style="margin:6px 0;"><strong>Date flexibility:</strong> ${escapeHtml(q.dateFlexibility)}</p>` : ''}
        ${q.preferredDate ? `<p style="margin:6px 0;"><strong>Preferred date:</strong> ${new Date(q.preferredDate).toLocaleDateString()}</p>` : ''}
      </div>

      <div style="background:#f0fdf4;border-left:4px solid #10b981;padding:18px;border-radius:8px;margin:18px 0;">
        <h3 style="color:#10b981;margin:0 0 10px 0;">💬 Their message</h3>
        <p style="color:#334155;font-style:italic;background:white;padding:12px;border-radius:6px;margin:0;">"${escapeHtml(args.message)}"</p>
      </div>

      <div style="text-align:center;margin-top:24px;">
        <a href="mailto:${encodeURI(args.userEmail)}" style="background:linear-gradient(135deg,#ec4899 0%,#8b5cf6 100%);color:white;padding:12px 24px;text-decoration:none;border-radius:8px;display:inline-block;font-weight:bold;">Reply now</a>
      </div>
    </div>
  </div>`;
}

function renderUserConfirmationEmail(args: {
  userName: string;
  venues: string[];
  guestCount: number;
}): string {
  return `<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:linear-gradient(135deg,#10b981 0%,#059669 100%);padding:20px;">
    <div style="background:white;border-radius:12px;padding:30px;">
      <h1 style="color:#10b981;margin:0 0 10px 0;">✅ Quotes requested from ${args.venues.length} venues</h1>
      <p style="color:#64748b;margin:0 0 18px 0;">Hi ${escapeHtml(args.userName)} — your wedding details (${args.guestCount} guests) are now in front of:</p>
      <ul style="color:#334155;line-height:1.8;">
        ${args.venues.map((v) => `<li>${escapeHtml(v)}</li>`).join('')}
      </ul>
      <p style="color:#334155;margin-top:20px;">Each venue knows you're considering several options, so expect prompt replies — most respond within 24-48 hours.</p>
    </div>
  </div>`;
}

function escapeHtml(value: string): string {
  if (value == null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}
