// Bulk-insert ~73 boutique Tier 1 wedding venues across Northeast Florida,
// Central Florida, and the Panhandle. Sourced from 5 parallel research
// agents (St. Augustine, Jacksonville/Ponte Vedra/Amelia, Orlando, Winter
// Park/Mount Dora/Sanford/Kissimmee, 30A/Destin, Pensacola/Apalachicola).
//
// Run via:
//   npx tsx scripts/insert-tier1-statewide-venues.ts

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config({ path: '/Users/bennettbonta/SoFloWeddingVenues/.env.production' });
config({ path: '.env.local', override: true });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing SUPABASE_URL or SERVICE_ROLE_KEY');
  process.exit(1);
}

interface NewVenue {
  name: string;
  city: string;
  venue_type: 'beach' | 'garden' | 'ballroom' | 'historic' | 'modern' | 'rustic';
  contact_website: string;
  contact_phone: string | null;
  description: string;
  capacity_min: number | null;
  capacity_max: number | null;
  price_min: number | null;
  amenities: string[];
}

const VENUES: NewVenue[] = [
  // ── ST. AUGUSTINE (10) ──
  { name: 'The Treasury on the Plaza', city: 'St. Augustine', venue_type: 'ballroom', contact_website: 'https://treasuryontheplaza.com', contact_phone: '904-217-0077', description: "Originally opened in the 1920s as a grand bank in downtown St. Augustine, this restored building still features marble columns and a Vault Bar built inside the original bank safe. The owner-operated venue handles both ceremonies and receptions in a single historic property on the Plaza de la Constitucion.", capacity_min: 40, capacity_max: 175, price_min: null, amenities: ['Vault Bar inside historic bank safe', 'Bridal suite', "Groom's getting-ready area", 'In-house catering', 'Open bar options', 'Day-of coordination', 'Exclusive single-event use'] },
  { name: 'The White Room', city: 'St. Augustine', venue_type: 'historic', contact_website: 'https://www.whiteroomweddings.com', contact_phone: '904-824-9056', description: "An 1888 waterfront building in the historic district at 1 King Street, billed as the only private waterfront wedding venue in downtown St. Augustine. The complex includes three connected spaces — the Grand Ballroom, the ground-floor Villa Blanca with vaulted ceilings, and a rooftop terrace overlooking Matanzas Bay.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Bayfront panoramic views', 'Grand Ballroom', 'Villa Blanca ceremony space', 'Rooftop terrace', 'In-house executive chef catering', 'On-site coordination', 'Bridal suites'] },
  { name: 'Lightner Museum', city: 'St. Augustine', venue_type: 'historic', contact_website: 'https://weddings.lightnermuseum.org', contact_phone: '904-217-0077', description: "Henry Flagler's 1888 Hotel Alcazar, now a city-owned museum; the main reception ballroom occupies the space that once held the world's largest indoor swimming pool. Couples use the Grand Lobby for cocktail hour and the historic Pool ballroom for dinner, with the Castillo de San Marcos and Flagler College campus right outside.", capacity_min: 40, capacity_max: 225, price_min: null, amenities: ['Historic Pool ballroom', 'Grand Lobby', 'Indoor and outdoor spaces', 'Private suites', 'On-site catering', 'In-house bar packages', 'Wedding coordination'] },
  { name: 'Markland House at Flagler College', city: 'St. Augustine', venue_type: 'historic', contact_website: 'https://www.flagler.edu', contact_phone: '904-829-6481', description: "A Greek-Revival estate home originally built in an orange grove and now on the National Register of Historic Places, located on the Flagler College campus. The property has a wrap-around covered porch, magnolia and oak-lined walks, and four interior rooms — the Library, Dining Room, and adjoining Pink and Yellow Rooms — used together for ceremonies and receptions.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Wrap-around porch', 'Outdoor garden grounds', 'Four historic interior rooms', 'On-site catering', 'Tents and string lighting available', '5 hours reception time'] },
  { name: 'Ximenez-Fatio House Museum', city: 'St. Augustine', venue_type: 'historic', contact_website: 'https://www.ximenezfatiohouse.org', contact_phone: '904-829-3575', description: "A 1798 Spanish-colonial coquina mansion on Aviles Street — billed as the oldest street in America — that hosted its first wedding in 1834. The walled private courtyard is shaded with banana plants, hibiscus, and citrus, lit at night with string lights against original coquina walls.", capacity_min: null, capacity_max: 100, price_min: null, amenities: ['Private walled courtyard', 'Tropical garden (banana, hibiscus, citrus)', 'Coquina-walled buildings', 'String lighting', 'Aviles Street access'] },
  { name: 'Pena-Peck House', city: 'St. Augustine', venue_type: 'garden', contact_website: 'https://penapeckhouse.com', contact_phone: '904-829-5064', description: "A First Spanish Period residence (1565-1763) built by royal decree of King Ferdinand VI, one of only about 35 First Spanish Period buildings still standing in St. Augustine. Weddings happen in the walled garden courtyard shaded by ancient oaks and magnolias, with indoor space available in the historic house.", capacity_min: 30, capacity_max: 125, price_min: 2000, amenities: ['Walled garden courtyard', 'Ancient oaks and magnolias', 'Tables/chairs for 125 included', 'Bridal dressing room', 'Indoor and outdoor space'] },
  { name: '9 Aviles', city: 'St. Augustine', venue_type: 'modern', contact_website: 'https://9avilesstreet.com', contact_phone: '904-250-0905', description: "A 2,500 square foot intimate venue at the corner of Aviles Street and Artillery Lane in the historic downtown arts district. The interior pairs a vaulted ballroom ceiling and iron chandeliers with a balcony overlooking the floor, a custom lit bar, and a private gated patio.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Vaulted ballroom ceiling', 'Iron chandeliers', 'Private gated patio', 'Bridal lounge', 'Custom lit bar', 'Balcony', 'Catering kitchen', 'Sound system', 'Dance floor'] },
  { name: 'The Kenwood Inn', city: 'St. Augustine', venue_type: 'garden', contact_website: 'https://thekenwoodinn.com', contact_phone: '904-824-2116', description: "An 1865 inn in the historic downtown district described as St. Augustine's oldest bed and breakfast. Couples exchange vows in the walled garden courtyard around a koi pond and saltwater pool, with the entire 14-room inn available for full-property buyouts.", capacity_min: null, capacity_max: 125, price_min: 589, amenities: ['Walled garden courtyard with koi pond', 'Saltwater pool and lounge', '14 guest rooms', 'Formal dining room', 'Multiple porches', 'Full-inn buyout option'] },
  { name: 'Bliss by the Sea', city: 'Crescent Beach', venue_type: 'beach', contact_website: 'https://blissbythesea.org', contact_phone: '904-789-4544', description: "A waterfront venue at 7605 A1A S in Crescent Beach with a courtyard across the street from the Atlantic and a pier on the Matanzas Intercoastal Waterway. The 800 square foot indoor hall pairs with outdoor reception space and ten on-site Indochine suites for overnight guests.", capacity_min: 50, capacity_max: 80, price_min: null, amenities: ['Courtyard across from Crescent Beach', 'Intercoastal pier', '800 sq ft indoor hall', 'Full commercial kitchen', '10 Indochine suites', 'On-site parking'] },
  { name: 'Ocean Sands Beach Boutique Inn', city: 'Vilano Beach', venue_type: 'beach', contact_website: 'https://www.oceansandsvilanobeach.com', contact_phone: '904-799-7263', description: "An independently-operated oceanfront inn on Vilano Beach with a one-acre private beach for ceremonies and oceanfront rooms with balconies for guest blocks. The property markets itself directly as a boutique inn, with help on planning, decor, catering, and entertainment vendor coordination.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['1-acre private beach', 'Oceanfront rooms with balconies', 'Hot breakfast buffet', 'Beach and bike rentals', 'Guest room blocks', 'Vendor coordination'] },

  // ── JACKSONVILLE / PONTE VEDRA / AMELIA (15) ──
  { name: 'The Cummer Museum of Art and Gardens', city: 'Jacksonville', venue_type: 'garden', contact_website: 'https://www.cummermuseum.org', contact_phone: null, description: "An art museum on the St. Johns River with historically significant formal gardens and indoor galleries that host weddings and private events. Ceremonies can take place beneath the 150-foot-canopy Cummer Oak in the Lower Tier Gardens, with receptions in the Terry Gallery or Uible Loggia.", capacity_min: 60, capacity_max: 300, price_min: 9000, amenities: ['Indoor galleries', 'Upper and Lower Tier Gardens', 'Tables and chairs', 'Preparation rooms', 'Exclusive in-house catering', 'Parking'] },
  { name: 'Brick and Beam', city: 'Jacksonville', venue_type: 'modern', contact_website: 'https://brickandbeamjax.com', contact_phone: '904-510-2168', description: "A 2,300 sq ft restored building in Jacksonville's Historic Springfield District blending exposed-brick industrial detail with a back-porch garden. Couples have full-day exclusive access to the indoor parlor and an outdoor space with gazebo, string lights, and firepit.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Exposed brick interior', 'Outdoor back porch', 'Fire pit', 'Bridal suite', 'Warming kitchen', 'Tables and chairs included', 'String lights'] },
  { name: 'The Glass Factory', city: 'Jacksonville', venue_type: 'modern', contact_website: 'https://www.theglassfactory.com', contact_phone: '904-414-5277', description: "A 16,000 sq ft former industrial space at 601 Myrtle Ave N featuring eclectic brick-and-beam architecture and customizable open-floor layouts. The venue includes a vintage furniture collection, bridal suite, groom's lounge, and all-day building access for couples.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['16,000 sq ft customizable space', 'Vintage furniture included', 'Bridal suite', "Groom's lounge", 'Climate control', 'On-site security'] },
  { name: 'Garden Club of Jacksonville', city: 'Jacksonville', venue_type: 'garden', contact_website: 'https://www.gardenclubjax.org', contact_phone: '904-355-4224', description: "A historic waterfront clubhouse in Riverside overlooking the St. Johns River, run as a private event venue by a nonprofit garden club. The Grand Ballroom features crystal chandeliers and floor-to-ceiling windows, and a courtyard with a tiered fountain hosts outdoor ceremonies.", capacity_min: 50, capacity_max: 350, price_min: null, amenities: ['Grand Ballroom with chandeliers', 'Historic Clubroom', 'Courtyard with fountain', 'Full catering kitchen', 'Stage', 'River views'] },
  { name: 'The Ribault Club', city: 'Jacksonville', venue_type: 'historic', contact_website: 'https://theribaultclub.com', contact_phone: '904-251-1050', description: "A 16,000 sq ft 1928 clubhouse on Fort George Island designed by Swiss architect Maurice Fatio, listed on the National Register of Historic Places. The venue blends restored architectural details — fluted pilasters, French doors, paneled woodwork — with coastal park grounds.", capacity_min: 25, capacity_max: 400, price_min: 6800, amenities: ['6,000 sq ft event space', '12-foot ceilings', '36 French doors to veranda', 'Bridal and groom prep rooms', 'On-site parking', 'AV screens', 'ADA accessible'] },
  { name: 'Casa Marina Hotel and Restaurant', city: 'Jacksonville Beach', venue_type: 'historic', contact_website: 'https://www.casamarinahotel.com', contact_phone: '904-270-0025', description: "An independently owned 1925 oceanfront hotel and Historic Hotels of America member at 691 1st St N, billed as a Jacksonville Beach landmark. The property hosts ceremonies and receptions in its dining room, rooftop terrace, and beachfront courtyard.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Rooftop terrace', 'Private beach access', 'Dining room', 'Beachfront courtyard', 'Guest rooms', 'In-house catering'] },
  { name: 'Private 131', city: 'Jacksonville Beach', venue_type: 'modern', contact_website: 'https://www.private131.com', contact_phone: '904-946-0122', description: "An upscale private event venue at 131 1st Ave N in Jacksonville Beach overlooking Latham Park, with beachfront views and a generous balcony. The space includes an event ballroom, marble bar, and patio area outfitted with state-of-the-art AV equipment.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Beachfront balcony', 'Marble bar', 'Ballroom', 'Patio', 'AV equipment', 'Upscale furnishings'] },
  { name: 'Aqua Grill', city: 'Ponte Vedra Beach', venue_type: 'modern', contact_website: 'https://www.aquagrill.net', contact_phone: '904-285-3017', description: "An independent contemporary restaurant established in 1988 at 395 Front Street, Ponte Vedra Beach, situated on a lake. The venue offers private dining services, full bar and grill, seasonal menus, and a dedicated private events program.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Private dining rooms', 'Lakeside setting', 'Full bar', 'In-house catering', 'Seasonal menus'] },
  { name: 'South Ponte Vedra Ocean Club', city: 'Ponte Vedra Beach', venue_type: 'beach', contact_website: 'https://www.spvoceanclub.com', contact_phone: '904-638-8422', description: "An oceanfront private-event restaurant at 3175 S Ponte Vedra Blvd offering on-site dining and ceremony space directly on the Atlantic. Bookings are accepted from non-members, and the venue has on-site chef and professional event staff.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Oceanfront views', 'On-site chef', 'Full-service dining', 'Handcrafted cocktails', 'Private event space'] },
  { name: 'Bagby Properties Oceanfront Wedding Homes', city: 'Ponte Vedra Beach', venue_type: 'beach', contact_website: 'https://bagbyproperties.com', contact_phone: '904-330-8089', description: "Veteran-owned luxury oceanfront vacation homes in South Ponte Vedra Beach (flagship homes at 2773 and 2777 S. Ponte Vedra Blvd) booked for weddings and private events. Properties feature oceanview decks, rooftop spaces, and private beach access.", capacity_min: null, capacity_max: 80, price_min: null, amenities: ['Private beach access', 'Oceanview decks', 'Rooftop spaces', 'Indoor and outdoor event areas', 'Wedding planner partner network'] },
  { name: 'Hoyt House', city: 'Fernandina Beach', venue_type: 'historic', contact_website: 'https://hoythouse.com', contact_phone: '904-277-4300', description: "A 1905 Victorian mansion in Fernandina Beach's Historic District, run as a 10-room boutique B&B with lush gardens and 250-year-old oaks. Hosts elopement and small-wedding packages with ceremonies in the gazebo or indoor parlor.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['10 guest rooms', 'Garden gazebo', 'Parlor for indoor ceremonies', 'Heated pool and hot tub', 'Gourmet breakfast', 'Private balconies'] },
  { name: 'Amelia Island Williams House', city: 'Fernandina Beach', venue_type: 'historic', contact_website: 'https://www.williamshouse.com', contact_phone: '904-277-2328', description: "An 1856 home, one of the oldest in Fernandina Beach, still surrounded by its original iron fence. Specializes in elopements and intimate weddings of up to 10 guests in the parlor, grand hallway, or first- and second-floor porches.", capacity_min: null, capacity_max: 10, price_min: 750, amenities: ['Parlor', 'Grand hallway', 'Two-floor porches', 'Gardens', 'Officiant included', 'Wedding cake', 'Heirloom bouquet', 'Champagne toast'] },
  { name: 'Florida House Inn', city: 'Fernandina Beach', venue_type: 'historic', contact_website: 'https://www.floridahouse.com', contact_phone: '904-491-3322', description: "Built in 1857, the oldest surviving hotel in Florida, located at 22 South 3rd Street in downtown Fernandina Beach. Wedding ceremonies and receptions take place in the fenced courtyard garden under a 300-year-old live oak, with 17 guest rooms on site.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Fenced courtyard garden', 'Two courtyards plus back porch', '300-year-old live oak', 'Mermaid Fountain', 'In-house catering and full bar', '17 guest rooms', 'Ivy-covered gazebo'] },
  { name: 'The Lesesne House', city: 'Fernandina Beach', venue_type: 'historic', contact_website: 'https://www.shgcollection.com', contact_phone: '904-302-3324', description: "An 1856-1860 Greek Revival residence at 415 Centre Street, the oldest continuously inhabited home in Fernandina Beach and a National Historic Landmark. Two courtyards, a grapevine pergola, formal dining and parlor rooms host intimate weddings and receptions.", capacity_min: null, capacity_max: 160, price_min: null, amenities: ['Private gardens and two courtyards', 'Grapevine pergola', 'Formal dining room', 'Two parlor rooms', 'Bridal room', "Gentleman's study"] },
  { name: 'The Ocean Club of Amelia', city: 'Amelia Island', venue_type: 'beach', contact_website: 'https://www.shgcollection.com', contact_phone: '904-302-3324', description: "An oceanfront private venue at 2080 S. Fletcher Avenue offering 3,900 sq ft of indoor and outdoor space directly on the Atlantic with public beach access. Features a main dining room, back porch, downstairs covered patio, and lawn area with driftwood-and-string-light coastal styling.", capacity_min: null, capacity_max: 250, price_min: null, amenities: ['Main dining room', 'Upstairs porch with ocean views', 'Covered patio and lawn', 'Direct beach access', 'Catering kitchen', 'Dual bars', 'ADA accessible'] },

  // ── ORLANDO / LAKE BUENA VISTA / APOPKA / WINTER GARDEN (9) ──
  { name: 'Dr. Phillips House', city: 'Orlando', venue_type: 'historic', contact_website: 'https://www.drphillipshouse.com', contact_phone: '407-693-5200', description: "A Victorian-era National Historic Landmark on Lake Lucerne in downtown Orlando, dating to the 1893 era and tied to citrus pioneer Dr. P. Phillips. The site doubles as a six-room boutique inn and offers garden ceremony space, a covered veranda, gazebo, and indoor Victorian rooms with French doors.", capacity_min: null, capacity_max: 250, price_min: null, amenities: ['Garden ceremony area', 'Gazebo', 'Covered veranda', 'Indoor Victorian dining rooms', 'On-site lodging (6 rooms)', 'Complimentary parking garage'] },
  { name: '1010 WEST', city: 'Orlando', venue_type: 'modern', contact_website: 'https://www.1010west.com', contact_phone: '321-444-3584', description: "A hidden former WWII airplane hangar in downtown Orlando reimagined as an industrial-chic event space with raw textures, edison market lighting, and a built-in bar. The single open-room layout supports flexible floorplans for intimate to large weddings.", capacity_min: 50, capacity_max: 250, price_min: 4200, amenities: ['8 hours of rental', '22 60-inch round tables', '12 cocktail tables', '150 mahogany chairs', 'Built-in bar', 'Edison market lighting', 'Valet parking for 125'] },
  { name: 'D Space Orlando', city: 'Orlando', venue_type: 'modern', contact_website: 'https://dspaceorlando.com', contact_phone: '407-505-5866', description: "A 6,000 sq ft modern-industrial venue with 20-foot black ceilings, polished concrete floors, a main gallery and second-floor mezzanine. Includes in-house catering through D'Loft Kitchen plus two private suites and full setup amenities.", capacity_min: 20, capacity_max: 400, price_min: null, amenities: ['8-12 hour rental', '2 private suites', 'In-house catering', 'Bar packages', 'Wi-Fi', 'Uplighting', '20-foot drapery'] },
  { name: 'The Acre Orlando', city: 'Orlando', venue_type: 'garden', contact_website: 'https://www.theacreorlando.com', contact_phone: '407-704-5161', description: "A one-acre rustic-urban sanctuary in Orlando's College Park neighborhood featuring lush gardens, fire pit areas, hammocks, multiple bars, and an indoor Chapel Hall. Designed as an eclectic, artistic outdoor-focused wedding setting.", capacity_min: 50, capacity_max: 300, price_min: 3500, amenities: ['Lush gardens', 'Fire pit', 'Multiple bars', 'Chapel Hall (indoor)', 'Hammock area', 'Preferred caterer network'] },
  { name: 'Paradise Cove', city: 'Lake Buena Vista', venue_type: 'garden', contact_website: 'https://paradisecoveorlando.com', contact_phone: '407-239-6939', description: "A tucked-away lakeside oasis on the shores of Lake Bryan featuring a sandy beach, palm-thatched cabana bar, tiki torches, and tropical island ambience. Offers all-inclusive wedding packages with on-site coordination.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Sandy lakefront beach', 'Palm-thatched cabana bar', 'Tiki torches', 'Cypress and lake views', 'Multiple ceremony/reception spaces', 'On-site coordination'] },
  { name: 'The Highland Manor', city: 'Apopka', venue_type: 'historic', contact_website: 'https://eventsbydubsdread.com', contact_phone: '407-650-9558', description: "A 110-year-old historic manor in downtown Apopka offering grand vintage Southern charm, four distinct event spaces (including the Crystal Ballroom and Oak Room), and grounds anchored by a 110-year-old oak tree. Full-service venue with in-house catering through Events by Dubsdread.", capacity_min: 20, capacity_max: 350, price_min: null, amenities: ['4 distinct indoor/outdoor spaces', 'Crystal Ballroom', 'Oak Room', 'In-house catering', 'Tableware and linens included', 'Bridal suite', '110-year-old oak ceremony site'] },
  { name: 'Club Lake Venue', city: 'Apopka', venue_type: 'rustic', contact_website: 'https://clublakevenue.com', contact_phone: null, description: "A 43-acre family-run ranch in rural Apopka with two lakes, mature live oak hammocks, a secret garden, the Whiskey River Bar, an air-conditioned reception hall with chandeliers, and a lakeside gazebo. Offers tiered all-inclusive wedding packages with month-of coordination, catering, bar service, and DJ.", capacity_min: 50, capacity_max: 200, price_min: null, amenities: ['43-acre property', 'Two lakes', 'Live oak ceremony hammock', 'Lakeside gazebo', 'Air-conditioned reception hall', 'Secret garden', 'Whiskey River Bar', 'Multiple getting-ready suites'] },
  { name: 'Hidden Barn Venue', city: 'Apopka', venue_type: 'rustic', contact_website: 'https://hiddenbarnvenue.com', contact_phone: '407-723-7986', description: "A 20-acre rustic barn property in Apopka with multiple themed event spaces including a chapel, western saloon, courtyard with waterfall feature, pool area, and bridal suite. Offers DIY and all-inclusive wedding packages with in-house coordination.", capacity_min: null, capacity_max: null, price_min: 4750, amenities: ['Chapel', 'Western Saloon', 'Pool and courtyard', 'Bridal suite', 'Waterfall photo feature', 'All-inclusive catering and bar'] },
  { name: 'Heller Hall', city: 'Winter Garden', venue_type: 'historic', contact_website: 'https://www.wghf.org', contact_phone: '407-656-3244', description: "An intimate event hall in the Healthy West Orange Heritage and Cultural Center within Winter Garden's downtown historic district, featuring high ceilings, chandelier, and large windows opening onto a 600 sq ft pergola. Sits along the West Orange Trail in the brick-lined historic core.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['1,054 sq ft indoor hall', 'Adjoining pergola (600 sq ft)', 'Tables and chairs included', 'A/V systems', 'Kitchenette', 'On-site parking'] },

  // ── WINTER PARK / MOUNT DORA / SANFORD / KISSIMMEE (17) ──
  { name: 'Casa Feliz Historic Home Museum', city: 'Winter Park', venue_type: 'historic', contact_website: 'https://www.casafelizvenue.com', contact_phone: '407-628-0230', description: "Award-winning 1932 Spanish farmhouse designed by architect James Gamble Rogers II, with original Spanish roof tiles, whitewashed century-old brick, and a bell tower. Restored interiors evoke 19th-century Spain across living room, library, courtyards, and a twinkling courtyard with market lights.", capacity_min: null, capacity_max: 120, price_min: 2000, amenities: ['Multiple indoor + courtyard spaces', "In-house catering via Arthur's", 'Garden room', 'Library', 'Bell tower', 'Historic interiors'] },
  { name: 'The Capen House', city: 'Winter Park', venue_type: 'historic', contact_website: 'https://capenhouse.com', contact_phone: '407-636-9316', description: "Restored 1885 Tudor Revival home famously floated by barge across Lake Osceola in 2013 and reassembled at the Polasek Museum's three-acre lakefront grounds. Features original heart-pine floors, vintage fixtures, an indoor veranda overlooking the lake, and an expansive lakefront patio.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Lakefront lawn (Lake Osceola)', '2,500+ sq ft event space', 'Hospitality suite', 'Sculpture garden setting', 'Indoor veranda', 'Lake-view patio'] },
  { name: 'Azalea Lodge at Mead Botanical Garden', city: 'Winter Park', venue_type: 'garden', contact_website: 'https://www.meadgarden.org', contact_phone: '407-650-9558', description: "Set within a 48-acre botanical garden featuring century-old oaks, the Azalea Lodge is a 2,400 sq ft indoor space paired with a Historic Little Amphitheater shaded by pink azaleas. Multiple ceremony spots include the Butterfly Garden, Camellia Garden, and Alice's Pond.", capacity_min: 20, capacity_max: 175, price_min: null, amenities: ['Indoor lodge + outdoor amphitheater', 'Bridal suite', 'Tables/chairs/china/glassware/linens included', 'Parking', 'In-house catering by Dubsdread'] },
  { name: 'Chapel and Cellar', city: 'Winter Park', venue_type: 'historic', contact_website: 'https://www.chapelandcellar.com', contact_phone: '407-842-8556', description: "Restored 1935 chapel paired with a rustic, leather-and-oak Cellar lounge and a fountain courtyard at the entrance of Hannibal Square, one block from Park Avenue. Designed for intimate ceremonies, rehearsal dinners, and micro-weddings.", capacity_min: null, capacity_max: 49, price_min: null, amenities: ['1935 chapel', 'Cellar lounge', 'Courtyard with fountain', 'Preferred caterers', 'Day-of coordination'] },
  { name: 'Knowles Memorial Chapel at Rollins College', city: 'Winter Park', venue_type: 'historic', contact_website: 'https://www.rollins.edu', contact_phone: '407-646-2115', description: "Built in 1932 and listed on the National Register of Historic Places, Knowles features dramatic stone towers, stained-glass windows, and a vintage pipe organ. The adjacent Rice Family Pavilion handles receptions on Rollins' lakefront campus.", capacity_min: null, capacity_max: 230, price_min: null, amenities: ['Historic chapel', 'Pipe organ', 'Stained glass', 'Rice Family Pavilion for receptions', 'Lakeside campus grounds'] },
  { name: 'Sydonie Mansion', city: 'Mount Dora', venue_type: 'historic', contact_website: 'https://sydoniemansion.com', contact_phone: '321-236-1534', description: "Historic 22,000 sq ft estate originally built in 1883 with 42 rooms, century-old oaks, a wrap-around covered porch, Spanish courtyard, boathouse, and lakeside views. Couples marry under live oaks, host cocktails in the courtyard, and dance on the massive porch.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Wrap-around porch', 'Spanish courtyard', 'Boathouse', 'Bridal suite', 'White wedding chairs and tables', 'Parking attendant'] },
  { name: 'Lakeside Inn', city: 'Mount Dora', venue_type: 'historic', contact_website: 'https://lakeside-inn.com', contact_phone: '800-556-2016', description: "Established 1883 — Florida's oldest continuously operating hotel and last surviving grand Victorian-era resort in Central Florida. Five yellow-and-white Victorian buildings line Lake Dora with a 200-foot rocking-chair verandah and lakefront docks.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['~5,000 sq ft indoor function space', 'Lakefront verandah', 'Beauclaire dining room', 'Two docks', 'Boat tours', '90 historic guest rooms'] },
  { name: 'Mount Dora Yacht Club', city: 'Mount Dora', venue_type: 'historic', contact_website: 'https://www.mountdorayachtclub.com', contact_phone: '352-383-3188', description: "Florida's oldest inland yacht club, established 1913, with floor-to-ceiling windows over Lake Dora and sunset views from a screened pavilion. Newly renovated lakefront clubhouse in historic downtown Mount Dora with private parking.", capacity_min: null, capacity_max: 150, price_min: 2000, amenities: ['Lakefront views', 'Screened pavilion', 'Commercial kitchen', 'Sound system + dance floor', 'Projector', 'Private parking', 'Bar'] },
  { name: 'Pegasus Manor', city: 'Mount Dora', venue_type: 'rustic', contact_website: 'https://pegasusmanor.com', contact_phone: null, description: "Ten-acre countryside estate with a quaint chapel, oak-and-pine hammock ceremony grove, covered outdoor reception, poolside cocktail area, pond, and working windmill. Distinguished by an on-site after-party Dance Hall, Bar and Lounge.", capacity_min: 50, capacity_max: 300, price_min: 6250, amenities: ['Chapel', 'Covered reception', 'After-party dance hall and bar', 'Pool deck', 'Pond', 'Windmill', '10 acres of grounds'] },
  { name: '520 on the Water', city: 'Sanford', venue_type: 'modern', contact_website: 'https://www.venue520.com', contact_phone: '407-325-1376', description: "Waterfront wedding venue directly on Lake Monroe overlooking the Sanford RiverWalk Trail and Veterans Memorial Park. Flexible BYO-vendor policy with sailboat-and-palm vistas; located just steps from historic downtown Sanford's shops and cafes.", capacity_min: null, capacity_max: null, price_min: 2000, amenities: ['Lake Monroe views', 'RiverWalk-adjacent', 'BYO catering/bar/decor', 'Appointment-only tours'] },
  { name: 'Historic Venue 1902', city: 'Sanford', venue_type: 'historic', contact_website: 'https://www.venue1902.com', contact_phone: null, description: "Locally husband-and-wife-owned 20,000+ sq ft former 1902 grammar school spanning a full city block in walkable downtown Sanford. Features a Grand Ballroom, separate bridal and grooms suites, library, and indoor/outdoor ceremony spaces.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Grand Ballroom', 'Bridal suite', 'Grooms room', 'Library', 'Classroom', 'Valet parking', '3D event renderings'] },
  { name: 'Sanford Galleon', city: 'Sanford', venue_type: 'modern', contact_website: 'https://sanfordgalleon.com', contact_phone: '321-441-3030', description: "Fully remodeled 4,000 sq ft event space along the St. Johns River shoreline of Lake Monroe with a 70-foot wall of floor-to-ceiling windows. Nautical-themed interior with cedar wood ceiling, beam chandeliers, and a Pirate Bar.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Floor-to-ceiling water-view wall', 'Full bar', 'ADA accessible', "Captain's Quarters conference room", 'Sternwheeler cruise option'] },
  { name: 'The Barn at Hidden Oaks Farm', city: 'Lake Mary', venue_type: 'rustic', contact_website: 'https://www.hiddenoaksbarn.com', contact_phone: '407-900-6972', description: "Distinctive black-and-white event barn measuring 64x84 feet with a trio of chandeliers, hand-crafted exposed beam structure, and full climate control. Set on a quiet farm with on-site animals along the Markham Woods corridor.", capacity_min: 1, capacity_max: 200, price_min: 5450, amenities: ['Climate-controlled barn', 'Two getting-ready suites', 'White garden chairs', 'Round tables and chestnut x-back chairs', 'AV equipment', 'Catering kitchen'] },
  { name: 'Pioneer Village at Shingle Creek', city: 'Kissimmee', venue_type: 'historic', contact_website: 'https://osceolahistory.org', contact_phone: '407-396-8644', description: "Ten-acre historic property featuring an 1800s replica church, original Florida pioneer buildings, a restored barn, ancient oak trees, and a screened pavilion. Operated by the Osceola County Historical Society near Lake Tohopekaliga.", capacity_min: 5, capacity_max: 1000, price_min: null, amenities: ['1800s replica church', 'Historic buildings', 'Barn', 'Screened pavilion', 'No vendor restrictions', '10 acres'] },
  { name: 'Wanderlust Okto', city: 'Orlando', venue_type: 'rustic', contact_website: 'https://oktohospitalitygroup.com', contact_phone: '954-937-7299', description: "Part wedding venue, part staycation property in Lake Nona, 5 minutes from Orlando International. Features a 4,000 sq ft climate-controlled enclosed barn, on-site treehouse, pond with wildlife, plus Airbnb cottages, an Airstream, and a container house for stays.", capacity_min: null, capacity_max: 200, price_min: null, amenities: ['Climate-controlled barn', 'Treehouse', 'Pond', 'Airstream and container house lodging', 'In-house event coordination', 'Bar setups', 'Tents'] },
  { name: 'Dockside Lake Nona', city: 'Orlando', venue_type: 'modern', contact_website: 'https://www.docksidelakenona.com', contact_phone: '407-455-3435', description: "Lakeside modern event venue in Lake Nona centered on The Lakehouse — a 2,000 sq ft space with rustic wood floors, oversized chandeliers, and warm industrial brick walls — paired with Tom Fruin's installation-art Glasshouse for ceremonies.", capacity_min: null, capacity_max: 120, price_min: null, amenities: ['Lakefront views', 'Tom Fruin Glasshouse ceremony space', 'Exclusive catering by Canvas Restaurant', 'Modern industrial interior'] },
  { name: 'Lavender on the Lake', city: 'St. Cloud', venue_type: 'rustic', contact_website: 'https://lavenderonthelakeevents.com', contact_phone: null, description: "Family-owned working fresh-cut flower farm and hops yard set on Lake Tohopekaliga (the same lake as Kissimmee's Lakefront Park). A luxury barn with 30-foot ceilings and giant glass garage doors anchors the 10-acre property.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['30 foot ceiling luxury barn', 'Glass garage doors', 'Lakefront on Lake Toho', 'Working flower farm', 'U-pick and workshops', '10 acres'] },

  // ── 30A / DESTIN (14) ──
  { name: 'WaterColor Inn', city: 'Santa Rosa Beach', venue_type: 'beach', contact_website: 'https://www.watercolorresort.com', contact_phone: '850-534-5017', description: "A AAA Four Diamond boutique inn nestled on the Gulf of Mexico inside the WaterColor community, with multiple ceremony and reception sites scattered around Western Lake, Marina Park, and the beach. Wedding packages bundle the venue, premium bar service, plated or strolling dinner, dance floor, and an overnight stay for the couple.", capacity_min: 50, capacity_max: 450, price_min: null, amenities: ['Beachfront', 'Lakefront LakeHouse and BoatHouse', 'Marina Park lawns', 'In-house catering', 'Premium open bar', 'Indoor backup space', 'On-site lodging'] },
  { name: 'The Pearl Hotel', city: 'Rosemary Beach', venue_type: 'ballroom', contact_website: 'https://www.thepearlrb.com', contact_phone: '850-460-9040', description: "A 55-room boutique hotel anchoring Rosemary Beach's main square, offering four event spaces from the Pearl Ballroom to the Havana Beach Rooftop overlooking the Gulf. Wedding packages are turnkey: catering, bar, AV, and lodging are all in-house.", capacity_min: null, capacity_max: 125, price_min: null, amenities: ['Pearl Ballroom (1,349 sq ft)', 'Havana Beach Rooftop with Gulf views', 'Hemingway Room', 'In-house catering', 'Spa Pearl', '55 guest rooms', 'Professional AV'] },
  { name: 'The Court at Seaside', city: 'Seaside', venue_type: 'garden', contact_website: 'https://www.thecourtseaside.com', contact_phone: '866-595-7178', description: "An eight-bungalow luxury boutique hotel arranged around a manicured central courtyard in the heart of Seaside, steps from the amphitheater and the beach. The garden courtyard hosts ceremonies and the three-story Ivory Tower serves as a bridal suite, with the entire property buyable-out for a vacation with a wedding weekend.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Landscaped garden courtyard', 'Ivory Tower bridal suite', '8 boutique residences', 'Complimentary bike rentals', 'Pool passes', 'Beach access', 'Concierge'] },
  { name: "Bud and Alley's Waterfront Restaurant", city: 'Seaside', venue_type: 'beach', contact_website: 'https://www.budandalleys.com', contact_phone: '850-830-9275', description: "An iconic Seaside waterfront restaurant operating for nearly 30 years, with six event spaces ranging from the rooftop Tarpon Club to the Gulf View Herb Garden Deck. Hosts rehearsal dinners, ceremonies, and full receptions on the white sand directly out front.", capacity_min: null, capacity_max: 200, price_min: null, amenities: ['Tarpon Club rooftop', 'Gulf View Herb Garden Deck', '30A-facing Sun Deck', 'Gulf View Porch', 'Main Dining Room', 'In-house Southern coastal catering'] },
  { name: 'Lyceum Lawn at Seaside', city: 'Seaside', venue_type: 'garden', contact_website: 'https://seasidefl.com', contact_phone: null, description: "The civic-district lawn at the heart of Seaside, framed by a two-story public walkway and a permanent event stage. Bookable directly through Seaside for tented receptions or open-air ceremonies in the town's most photographed spot.", capacity_min: null, capacity_max: 200, price_min: null, amenities: ['Permanent stage', 'Two-story surrounding walkway', 'Central Seaside town location', 'Tented reception capable', 'Walking distance to chapel and beach'] },
  { name: 'The Chapel at Seaside', city: 'Seaside', venue_type: 'historic', contact_website: 'https://thechapelatseaside.com', contact_phone: '850-633-3392', description: "Seaside's iconic white chapel with vaulted ceilings, stained glass, and a recognizable bell tower, offering interfaith ceremonies just steps from the Gulf. Rentals include three hours in the chapel plus a two-hour rehearsal slot.", capacity_min: null, capacity_max: 175, price_min: null, amenities: ['Vaulted ceilings with natural light', 'Bell tower', 'Interfaith celebrant access', 'Stained glass', '3-hour ceremony block + 2-hour rehearsal', 'Steps from the Gulf'] },
  { name: 'Vue on 30A', city: 'Santa Rosa Beach', venue_type: 'modern', contact_website: 'https://vueon30a.net', contact_phone: '850-267-2305', description: "A contemporary Gulf-front venue in the Santa Rosa Beach Country Club with floor-to-ceiling windows and an outdoor terrace, named Best Wedding Venue by Visit South Walton. Rental fee is unusually inclusive — tables, chairs, linens, china, glassware, bridal suite, and parking all bundled.", capacity_min: 20, capacity_max: 200, price_min: null, amenities: ['Floor-to-ceiling Gulf views', 'Main Terrace', 'West Wing', 'Beach ceremony', 'Bridal suite', 'Tables/chairs/linens/china included', 'On-site catering'] },
  { name: 'Hibiscus Coffee and Guesthouse', city: 'Santa Rosa Beach', venue_type: 'garden', contact_website: 'https://hibiscusflorida.com', contact_phone: '850-231-2733', description: "A 13-room family-owned guesthouse in Grayton Beach with a string-lit garden venue called the Backyard of Love, set under mature oaks with a custom bar and performance stage. Hosts intimate ceremonies, rehearsal dinners, and bridal brunches in a relaxed Old Florida setting.", capacity_min: null, capacity_max: 100, price_min: null, amenities: ['Mature oaks with string lighting', 'Custom bar', 'Performance stage', 'Vintage garden sculptures', '13 on-site guest rooms', 'On-site cafe', 'Pet friendly'] },
  { name: 'Monet Monet', city: 'Santa Rosa Beach', venue_type: 'garden', contact_website: 'https://www.monetmonet30a.com', contact_phone: '850-231-1090', description: "A garden venue in Grayton Beach styled after Claude Monet's Giverny home, with a lily pond, Japanese footbridge, bubbling fountains, and an indoor gallery. Operated exclusively by Grayton Beach Catering and Events.", capacity_min: null, capacity_max: 200, price_min: null, amenities: ['Lily pond', 'Japanese footbridge', 'Bubbling fountains', 'Indoor gallery space', 'Extensive flower gardens', 'Exclusive in-house catering'] },
  { name: 'Eden Gardens State Park', city: 'Santa Rosa Beach', venue_type: 'historic', contact_website: 'https://www.friendsofedengardens.com', contact_phone: '850-267-8320', description: "A 163-acre state park surrounding the 1890s Wesley House mansion, with a 600-year-old live-oak Wedding Tree, rose garden, and screened pavilion overlooking Tucker Bayou. Bookings are exclusive — only one wedding per day.", capacity_min: null, capacity_max: 100, price_min: null, amenities: ['600-year-old Wedding Oak', 'Wesley House (1890s mansion)', 'Screened pavilion with catering kitchen', 'Historic rose garden', '163-acre grounds', 'Exclusive single-event-per-day booking'] },
  { name: 'Camp Helen State Park', city: 'Inlet Beach', venue_type: 'historic', contact_website: 'https://www.floridastateparks.org', contact_phone: '850-233-5059', description: "A 180-acre state park where Lake Powell meets the Gulf, with a historic Depression-era lodge available for wedding rental. Reasonably priced for up to 100 guests with included tables and chairs; couples bring their own catering.", capacity_min: null, capacity_max: 100, price_min: null, amenities: ['Historic 1930s lodge overlooking Lake Powell', 'Gulf-front beach access', 'Tables and chairs included', '180 acres of grounds', 'BYO catering allowed'] },
  { name: 'Old Florida Fish House', city: 'Santa Rosa Beach', venue_type: 'modern', contact_website: 'https://www.oldfloridafishhouse.com', contact_phone: '850-534-3045', description: "An independent Seagrove Beach seafood restaurant on Eastern Lake with two main spaces — the central dining room and the open-air Porch — plus daily live music and a full sushi/oyster bar. Hosts rehearsal dinners and intimate receptions.", capacity_min: null, capacity_max: 300, price_min: null, amenities: ['Eastern Lake views', 'Covered Porch with full bar', 'Main dining room', 'Daily live music', 'Sushi and oyster bar', 'On-site catering'] },
  { name: 'Henderson Park Inn', city: 'Destin', venue_type: 'beach', contact_website: 'https://www.hendersonparkinn.com', contact_phone: '888-836-1105', description: "An adults-only boutique beachfront inn adjacent to Henderson Beach State Park, voted the most romantic hotel in North America by TripAdvisor. Hosts beach ceremonies on the lawn (up to 150) and intimate deck receptions overlooking a mile of undeveloped white sand.", capacity_min: null, capacity_max: 150, price_min: null, amenities: ['Beachfront lawns', 'Ocean-view deck', 'Beach Walk Cafe and Cantina on-site', 'Complimentary beach service', 'Guest accommodations', 'Adults-only privacy'] },
  { name: 'Marina Cafe', city: 'Destin', venue_type: 'modern', contact_website: 'https://marinacafe.com', contact_phone: '850-733-6446', description: "Destin's most-awarded restaurant, sitting on the Destin Harbor with a 30-foot window wall and wood-beamed dining room. Six event spaces handle everything from a 22-person engagement dinner to a 150-person reception, with full per-guest pricing tiers.", capacity_min: 22, capacity_max: 250, price_min: 75, amenities: ['Floor-to-ceiling harbor windows', 'Private dining room', 'Cocktail lounge', 'Main dining room', 'Submarina Beachside Deck', 'Two covered outdoor patios', 'Dance floor', 'Brick oven'] },

  // ── PENSACOLA / APALACHICOLA (8) ──
  { name: 'The Sanctuary 1905', city: 'Pensacola', venue_type: 'historic', contact_website: 'https://thesanctuary1905.com', contact_phone: '850-761-1905', description: "Originally built in 1905 as Sacred Heart Church, this Pensacola landmark has been restored into a multi-room event venue with an interior sanctuary, garden, and courtyard. The space pairs original early-1900s architecture with curated vendor partnerships for ceremonies and receptions.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Historic sanctuary interior', 'Garden', 'Courtyard', 'Preferred vendor list', 'Climate controlled'] },
  { name: '511 Palafox', city: 'Pensacola', venue_type: 'historic', contact_website: 'https://5elevenpalafox.com', contact_phone: '850-977-0180', description: "511 Palafox is a downtown Pensacola event venue on one of the country's recognized Great Streets, with three distinct spaces — The Hall, The Loft, and The Courtyard. Couples can hold ceremonies in the courtyard garden and move indoors for a reception. Featured in Garden and Gun, Vogue, and Southern Living.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['The Hall', 'The Loft', 'Outdoor courtyard', 'All-inclusive packages', 'Bridal suite'] },
  { name: 'Palafox Wharf Waterfront', city: 'Pensacola', venue_type: 'historic', contact_website: 'https://617palafoxwharf.com', contact_phone: '850-748-5102', description: "Built in 1880 as a shipping company on the Pensacola Bay marina, Palafox Wharf is an award-winning historic venue blending exposed brick and wooden beams with bay views. Packages include a 33 foot dance floor, 40 foot cocktail bar, café lights, and in-house planning support.", capacity_min: 30, capacity_max: 175, price_min: 5000, amenities: ['Waterfront deck', 'Lawn ceremonies', 'Interior hall', 'In-house planner', 'Dance floor', 'Cocktail bar'] },
  { name: 'Long Hollow Creatives', city: 'Pensacola', venue_type: 'historic', contact_website: 'https://www.longhollowcreatives.com', contact_phone: '850-712-5730', description: "Long Hollow Creatives occupies a circa-1905 former fire-station stable in downtown Pensacola, with original cobblestone floors, exposed brick, and timber beams. The venue is built around a Loft, a gated Courtyard with firepit, and a production studio — ideal for intimate weddings, elopements, and rehearsal dinners.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['The Loft', 'Gated courtyard with firepit', 'Production studio', 'Exposed brick and timber'] },
  { name: 'Pier Suite Events', city: 'Pensacola Beach', venue_type: 'beach', contact_website: 'https://piersuiteevents.com', contact_phone: '850-501-0409', description: "Pier Suite Events is an all-inclusive waterfront venue at the heart of Pensacola Beach with sweeping views of the emerald-green Gulf and white sand beaches. The space features a minimalist neutral interior, large windows, a private balcony, and a dressing room.", capacity_min: null, capacity_max: null, price_min: null, amenities: ['Gulf-view balcony', 'Dressing room', 'Open-floor interior', 'All-inclusive coordination'] },
  { name: 'The Gibson Inn', city: 'Apalachicola', venue_type: 'historic', contact_website: 'https://www.gibsoninn.com', contact_phone: '850-270-2190', description: "Opened in 1907 and listed on the National Register of Historic Places, the Gibson Inn anchors downtown Apalachicola with its wrap-around porches, Parlor Bar, and Palm Courtyard. Couples can choose from intimate spaces (the Buck House Parlor) up through a full-property buyout.", capacity_min: 8, capacity_max: 300, price_min: null, amenities: ['Palm Courtyard', 'Wrap-around porches', 'Parlor Bar', 'Franklin Café catering', 'Buck House', 'Sun Deck', 'Complimentary bike rentals'] },
  { name: 'Coombs Inn and Suites', city: 'Apalachicola', venue_type: 'historic', contact_website: 'https://www.coombsinnandsuites.com', contact_phone: '888-626-6627', description: "Coombs Inn and Suites is a restored Victorian mansion with antique furnishings, a grand staircase, original chandeliers, and gleaming wood floors. Ceremonies are held in the Camellia Gardens or inside the mansion, with the Camellia Hall carriage house available for receptions and the inn's dining room for rehearsal dinners.", capacity_min: null, capacity_max: 60, price_min: null, amenities: ['Camellia Gardens', 'Victorian mansion interior', 'Camellia Hall carriage house', '23 guest rooms', 'Private bridal parlor'] },
  { name: 'SunScape and SeaScape', city: 'Cape San Blas', venue_type: 'beach', contact_website: 'https://www.sunscapeseascape.com', contact_phone: '850-227-5869', description: "SunScape and SeaScape is a one-acre private beachfront estate on South Cape San Blas with eight bedrooms, ten baths, and overnight space for twenty. Couples have exclusive use of the property for the welcome party through the ceremony, with five distinct event areas including the beach, covered breezeway, and poolside.", capacity_min: 50, capacity_max: 100, price_min: 2000, amenities: ['One acre Gulf frontage', 'Screened pool and spa', 'Two condos', 'Elevator', 'BYO vendors', 'Sleeps 20'] },
];

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/'/g, '')
    .replace(/[.,'"`/\\]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

async function main() {
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false },
  });

  const rows = VENUES.map((v) => {
    const slug = `${slugify(v.name)}-${slugify(v.city)}`;
    return {
      legacy_id: slug,
      slug,
      tier: 'starter' as const,
      name: v.name,
      description: v.description,
      city: v.city,
      state: 'FL',
      capacity_min: v.capacity_min,
      capacity_max: v.capacity_max,
      venue_type: v.venue_type,
      price_min: v.price_min,
      amenities: v.amenities,
      tags: [],
      images: [],
      contact_phone: v.contact_phone,
      contact_email: null,
      contact_email_real: false,
      contact_website: v.contact_website,
    };
  });

  console.log(`Inserting ${rows.length} venues…`);
  const { data, error } = await supabase
    .from('venues')
    .upsert(rows, { onConflict: 'slug' })
    .select('slug, name, city, venue_type');

  if (error) {
    console.error('Insert failed:', error);
    process.exit(1);
  }

  console.log(`✓ ${data?.length ?? 0} venues upserted\n`);
  // Group by region for the report.
  const byCity = new Map<string, number>();
  for (const v of data ?? []) {
    byCity.set(v.city ?? '?', (byCity.get(v.city ?? '?') ?? 0) + 1);
  }
  console.log('By city:');
  for (const [city, count] of Array.from(byCity.entries()).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${count.toString().padStart(2)}  ${city}`);
  }
  // Print every slug for the watercolor batch.
  console.log('\nSlugs (for watercolor batch):');
  for (const v of data ?? []) console.log(`  ${v.slug}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
