// Bulk-insert 120 boutique vendors across the 6 newer Florida regions
// (tampa-bay + sarasota-bradenton + southwest-florida + northeast-florida
// + central-florida + panhandle). Sourced from 6 parallel research agents.
//
//   npx tsx scripts/insert-tier2-vendors.ts

import { createClient } from '@supabase/supabase-js';
import { config } from 'dotenv';

config({ path: '/Users/bennettbonta/SoFloWeddingVenues/.env.production' });
config({ path: '.env.local', override: true });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing SUPABASE_URL or SERVICE_ROLE_KEY');
  process.exit(1);
}

interface NewVendor {
  name: string;
  city: string;
  category: 'planner' | 'photographer' | 'florist' | 'baker';
  contact_website: string;
  contact_phone: string | null;
  contact_email: string | null;
  description: string;
  specialties: string[];
  service_area: string[];
}

const VENDORS: NewVendor[] = [
  // ── TAMPA BAY (20) ──
  { name: 'Events by Lindsay J', city: 'Tampa', category: 'planner', contact_website: 'https://www.eventsbylj.com', contact_phone: '813-469-1802', contact_email: 'hello@eventsbylj.com', description: "Owner-operated boutique wedding planning studio led by Lindsay J, specializing in full-service planning, design, and detailed coordination for Tampa Bay couples. Known across the area for high-touch service and elegant venue transformations.", specialties: ['full-service planning', 'wedding design', 'day-of coordination', 'luxury weddings'], service_area: ['Tampa', 'St. Petersburg', 'Clearwater'] },
  { name: 'EventFull Weddings', city: 'Tampa', category: 'planner', contact_website: 'https://www.eventfullweddings.com', contact_phone: '813-309-8559', contact_email: 'Karen@eventfullweddings.com', description: "Boutique Tampa wedding planning studio founded by Karen, a Tampa native who built EventFull around bridal concierge service, intentional design, and luxury-level execution. The team accepts a limited number of weddings each year to keep service highly personalized.", specialties: ['full-service planning', 'bridal concierge', 'luxury weddings'], service_area: ['Tampa', 'Tampa Bay'] },
  { name: 'The Olive Tree Weddings', city: 'Tampa', category: 'planner', contact_website: 'https://theolivetreeweddingsllc.com', contact_phone: '813-970-8573', contact_email: 'info@theolivetreeweddingsllc.com', description: "Owner-operated Tampa Bay planning studio led by Amanda offering full-service planning, partial planning, and 90-day or month-of coordination. Emphasizes a warm, friend-like client relationship.", specialties: ['full-service planning', 'month-of coordination', 'partial planning'], service_area: ['Tampa Bay', 'Florida'] },
  { name: 'Aulen Events', city: 'St. Petersburg', category: 'planner', contact_website: 'https://aulenevents.com', contact_phone: null, contact_email: null, description: "St. Pete-based boutique planning studio led by Jordan, offering tiered packages from day-of coordination to full design with access to Aulen's proprietary decor inventory.", specialties: ['day-of coordination', 'partial planning', 'full-service planning', 'decor styling'], service_area: ['St. Petersburg', 'Tampa', 'Sarasota'] },
  { name: 'Special Moments Event Planning', city: 'Largo', category: 'planner', contact_website: 'https://eventsbyspecialmoments.com', contact_phone: '727-343-0800', contact_email: 'info@eventsbyspecialmoments.com', description: "Tampa Bay planning company founded by Master Wedding Planner Tammy Waterman, one of only a handful of MWPs worldwide. Particularly known for cultural and multi-faith weddings (Greek, Nigerian, Jewish, Haitian, Egyptian, Ethiopian).", specialties: ['cultural weddings', 'destination weddings', 'full-service planning'], service_area: ['Largo', 'Tampa', 'St. Petersburg', 'Clearwater', 'Dunedin', 'Safety Harbor'] },
  { name: 'Stills by Hernan', city: 'Tampa', category: 'photographer', contact_website: 'https://stillsbyhernan.com', contact_phone: null, contact_email: null, description: "Tampa-based wedding photographer Hernan blending editorial, cinematic compositions with documentary candor for luxury and multicultural weddings. Bilingual English/Spanish.", specialties: ['editorial', 'cinematic', 'multicultural weddings', 'Super 8 film'], service_area: ['Tampa', 'Naples', 'Florida'] },
  { name: 'Djamel Photography', city: 'Tampa', category: 'photographer', contact_website: 'https://www.djamelphotography.com', contact_phone: null, contact_email: null, description: "Tampa-based fine art and editorial wedding photographer Djamel, twice named Photographer of the Year by the Florida Magazine Association, with 20+ years of editorial and advertising experience. Limits annual bookings.", specialties: ['fine art', 'editorial', 'LGBTQ weddings'], service_area: ['Tampa', 'Clearwater', 'St. Petersburg', 'Sarasota'] },
  { name: 'Carography Studios', city: 'Tampa', category: 'photographer', contact_website: 'https://carographystudios.com', contact_phone: '813-399-0847', contact_email: 'carolina@carographystudios.com', description: "Latina-owned boutique wedding photography studio in Tampa run by Carolina, capturing candid, emotionally-driven imagery and producing handcrafted Italian fine art albums. In business since 2015.", specialties: ['candid', 'documentary', 'fine art albums', 'bilingual'], service_area: ['Tampa', 'Tampa Bay'] },
  { name: 'Alera Weddings', city: 'St. Petersburg', category: 'photographer', contact_website: 'https://aleraweddings.com', contact_phone: null, contact_email: null, description: "St. Petersburg-based boutique wedding photo team founded by Alexis Bedenbaugh, specializing in documentary-style coverage with a timeless, true-to-color edit.", specialties: ['documentary', 'candid', 'true-to-color editing'], service_area: ['St. Petersburg', 'Tampa Bay'] },
  { name: 'McNeile Photography', city: 'St. Petersburg', category: 'photographer', contact_website: 'https://www.mcneilephotography.com', contact_phone: '727-237-4583', contact_email: null, description: "St. Pete and Tampa Bay wedding photographer Arron McNeile shooting authentic documentary coverage on digital alongside analog 35mm and Super 8 film.", specialties: ['documentary', 'film photography', 'Super 8 video', 'elopements'], service_area: ['St. Petersburg', 'Tampa Bay'] },
  { name: 'Marigold Flower Co', city: 'Tampa', category: 'florist', contact_website: 'https://www.marigoldflowerco.com', contact_phone: '813-518-5551', contact_email: 'hello@marigoldflowerco.com', description: "North Tampa wedding floral boutique focused on making the floral planning process easy, fun, and creative for couples. Real shop on N. Dale Mabry Hwy.", specialties: ['wedding florals', 'bridal bouquets', 'ceremony installations'], service_area: ['Tampa', 'St. Petersburg', 'Clearwater', 'Bradenton', 'Brandon'] },
  { name: 'Bruce Wayne Florals', city: 'St. Petersburg', category: 'florist', contact_website: 'https://www.brucewayneflorals.com', contact_phone: '727-800-6736', contact_email: 'john.bwflorals@gmail.com', description: "St. Petersburg event and wedding florist with a brick-and-mortar studio on 49th Street North, designing for small intimate celebrations through high-end design-forward weddings.", specialties: ['wedding florals', 'event installations', 'bridal bouquets'], service_area: ['St. Petersburg', 'Tampa Bay'] },
  { name: 'Arms of Persephone Floral Design', city: 'St. Petersburg', category: 'florist', contact_website: 'https://www.armsofpersephonefloral.com', contact_phone: '727-314-2277', contact_email: 'armsofpersephone@gmail.com', description: "St. Petersburg boutique florist run by Regan, designing playful, story-driven wedding florals built on seasonality and sustainability. Operates Florida's first flower drive-thru alongside their wedding work.", specialties: ['seasonal florals', 'sustainable design', 'wedding florals'], service_area: ['St. Petersburg', 'Pinellas Park'] },
  { name: 'Garden of Eden Floral Designs', city: 'Clearwater', category: 'florist', contact_website: 'https://www.gardenofedenfloraldesigns.net', contact_phone: '727-239-7089', contact_email: 'gardenofeden106@protonmail.com', description: "Clearwater-based wedding and resort florist specializing in bold, modern tropical blooms for beach ceremonies, yacht weddings, and luxury resort installations.", specialties: ['tropical florals', 'beach weddings', 'resort installations'], service_area: ['Clearwater', 'Clearwater Beach', 'Dunedin', 'Safety Harbor', 'Palm Harbor'] },
  { name: 'Art Le Fleur Flowers and Gifts', city: 'Clearwater', category: 'florist', contact_website: 'https://artlefleur.com', contact_phone: '727-271-4661', contact_email: 'artlefleur@gmail.com', description: "Mother-and-daughter Clearwater florist run by Giselle and Alina with a combined 30 years in floral design. Known for fresh peonies, ranunculus, dahlias, and protea in custom wedding work.", specialties: ['custom florals', 'weddings', 'specialty blooms'], service_area: ['Clearwater', 'Indian Rocks Beach', 'Dunedin', 'Largo', 'Tarpon Springs', 'St. Petersburg'] },
  { name: 'Hands On Sweets', city: 'Tampa', category: 'baker', contact_website: 'https://handsonsweets.com', contact_phone: null, contact_email: null, description: "Husband-and-wife Tampa wedding cake studio run by Marie and Carlos, designing scratch-baked custom cakes with formal pastry training and Spanish heritage.", specialties: ['custom wedding cakes', 'dessert tables', 'macarons', 'edible favors'], service_area: ['Tampa', 'Tampa Bay'] },
  { name: 'Wandering Whisk Bakeshop', city: 'Pinellas Park', category: 'baker', contact_website: 'https://www.wanderingwhiskbakeshop.com', contact_phone: null, contact_email: 'hello@wanderingwhiskbakeshop.com', description: "Appointment-only Pinellas Park bakeshop founded by Chef Jennifer, specializing in botanical wedding cakes adorned with fresh florals, hand-painted buttercream, and macaron towers.", specialties: ['botanical wedding cakes', 'buttercream design', 'macaron towers', 'dessert tables'], service_area: ['Pinellas Park', 'St. Petersburg', 'Tampa Bay'] },
  { name: 'The Artistic Whisk', city: 'St. Petersburg', category: 'baker', contact_website: 'https://www.theartisticwhisk.com', contact_phone: '727-350-4995', contact_email: 'info@theartisticwhisk.com', description: "St. Petersburg custom wedding bakery using all-natural scratch ingredients, premium imported European chocolate, and Swiss meringue buttercream. Offers 38 cake flavors plus full dessert bars.", specialties: ['custom wedding cakes', 'scratch baking', 'Swiss meringue buttercream', 'gluten-free'], service_area: ['St. Petersburg', 'Tampa', 'Clearwater', 'Sarasota'] },
  { name: 'Cakes by Carolynn', city: 'St. Petersburg', category: 'baker', contact_website: 'https://cakesbycarolynn.com', contact_phone: '727-327-5725', contact_email: null, description: "Family-owned St. Petersburg wedding cake bakery operating since 1989, named to The Knot Hall of Fame. Known for distinctive flavors like lemon blueberry and pina colada.", specialties: ['custom wedding cakes', "groom's cakes", 'specialty flavors'], service_area: ['St. Petersburg', 'Tampa Bay'] },
  { name: 'Lavender Ridge Photography', city: 'St. Petersburg', category: 'photographer', contact_website: 'https://www.lavenderridgephotography.com', contact_phone: null, contact_email: null, description: "St. Petersburg native photographer Shayla Cheyenne offering candid, vibrant wedding and elopement coverage with a relaxed, prompt-led posing approach.", specialties: ['candid', 'lifestyle', 'elopements'], service_area: ['St. Petersburg', 'Tampa Bay'] },

  // ── SARASOTA-BRADENTON (20) ──
  { name: 'Captivated By Weddings', city: 'Sarasota', category: 'planner', contact_website: 'https://captivatedbyweddings.com', contact_phone: null, contact_email: 'hello@captivatedbyweddings.com', description: "A boutique wedding planning and design studio in Sarasota run by Janeth and Karen, focused on intentional planning and design for romantic celebrations.", specialties: ['full planning and design', 'partial planning', 'month-of coordination'], service_area: ['Sarasota'] },
  { name: 'Laura Detwiler Events', city: 'Sarasota', category: 'planner', contact_website: 'https://www.lauradetwilerevents.com', contact_phone: null, contact_email: null, description: "Sarasota-based luxury wedding planner specializing in full-service planning, multi-day events, and event management. Boutique approach where clients work directly with owner Laura.", specialties: ['full-service planning', 'multi-day weddings', 'design and styling'], service_area: ['Sarasota', 'Tampa Bay'] },
  { name: 'Precious Moments Events', city: 'Sarasota', category: 'planner', contact_website: 'https://www.preciousmomentseventsllc.com', contact_phone: '941-301-9509', contact_email: 'Michelle@preciousmomentseventsllc.com', description: "Husband-and-wife team Michelle and Nelson Borrero run this Sarasota wedding planning firm. Both are certified planners and designers and offer bilingual English/Spanish service.", specialties: ['full planning', 'partial planning', 'design and decor', 'beach ceremony packages'], service_area: ['Sarasota', 'Anna Maria Island'] },
  { name: 'Karen and Company Event Planning', city: 'Bradenton', category: 'planner', contact_website: 'http://www.karenandco.pro', contact_phone: '518-857-2189', contact_email: null, description: "Bradenton-based wedding and event planning firm led by Karen Ricci, established in 2017. Offers tiered packages from a Kick-Off to Full Planning.", specialties: ['full planning', 'day-of coordination', 'vendor management'], service_area: ['Bradenton', 'Sarasota'] },
  { name: 'Always Special Events', city: 'Bradenton', category: 'planner', contact_website: 'https://www.alwaysspecialevents.com', contact_phone: null, contact_email: 'audra@alwaysspecialevents.com', description: "Sarasota and Bradenton wedding and event planner led by Audra, an Accredited Event Designer and Certified Wedding Planner. Provides planning, design, decorating, and ceiling draping.", specialties: ['wedding planning', 'event design and decor', 'draping and rentals', 'florals'], service_area: ['Sarasota', 'Bradenton', 'Lakewood Ranch'] },
  { name: 'Sandhill Photography', city: 'Bradenton', category: 'photographer', contact_website: 'https://www.sandhillphoto.com', contact_phone: '813-409-6512', contact_email: 'info@sandhillphoto.com', description: "Bradenton wedding and family photography studio owned by lead photographer Emma-Rose Triscritti. Storytelling approach informed by Emma-Rose's BFA background.", specialties: ['wedding photography', 'engagement', 'family', 'maternity'], service_area: ['Bradenton', 'Anna Maria Island', 'Longboat Key', 'Sarasota'] },
  { name: 'Love and Style Photography', city: 'Sarasota', category: 'photographer', contact_website: 'https://loveandstylephotography.com', contact_phone: '941-960-6485', contact_email: 'becky@loveandstylephotography.com', description: "Family-owned Sarasota photography studio led by Becky and a small team specializing in weddings, engagements, elopements, and family sessions. Decade-plus of experience.", specialties: ['weddings', 'engagements', 'elopements', 'family portraits'], service_area: ['Sarasota', 'Bradenton', 'Anna Maria Island', 'Siesta Key', 'Longboat Key'] },
  { name: 'Lindsey White Photography', city: 'Sarasota', category: 'photographer', contact_website: 'https://lindseywhitephoto.com', contact_phone: null, contact_email: 'lindseywhitephoto@gmail.com', description: "Sarasota luxury wedding photographer Lindsey White brings 11+ years of experience to elegant, light, and timeless wedding imagery across Florida.", specialties: ['luxury weddings', 'engagement sessions', 'albums and prints'], service_area: ['Sarasota', 'Bradenton'] },
  { name: 'Photography by Lisa E', city: 'Bradenton', category: 'photographer', contact_website: 'https://www.photographybylisae.com', contact_phone: '941-243-1945', contact_email: 'lisa@photographybylisae.com', description: "Bradenton-based West Coast Florida photographer specializing in weddings, beach portraits, family sessions, and corporate events. Serves the Suncoast within a 2-hour radius.", specialties: ['weddings', 'beach portraits', 'family', 'corporate events'], service_area: ['Bradenton', 'Anna Maria Island', 'Sarasota', 'Siesta Key'] },
  { name: 'Jaeger Haus Photography', city: 'Bradenton', category: 'photographer', contact_website: 'https://jaegerhausphotography.com', contact_phone: null, contact_email: null, description: "Bradenton local Kelsey Jaeger photographs weddings, elopements, engagements, and families with a natural-light, minimal-edit style. Anna Maria Island is her favorite location.", specialties: ['weddings', 'elopements', 'engagements', 'families'], service_area: ['Anna Maria Island', 'Bradenton', 'Sarasota', 'Siesta Key', 'Longboat Key'] },
  { name: 'Uprooted Rose', city: 'Sarasota', category: 'florist', contact_website: 'https://uprootedrose.com', contact_phone: '941-318-0643', contact_email: 'info@uprootedrose.com', description: "Sarasota luxury florist with a downtown storefront on Palm Avenue offering custom floral arrangements, sympathy work, workshops, and weddings.", specialties: ['luxury wedding floristry', 'custom arrangements', 'workshops', 'event florals'], service_area: ['Sarasota', 'Bradenton', 'Lakewood Ranch', 'Siesta Key', 'Longboat Key'] },
  { name: 'Fliorens', city: 'Sarasota', category: 'florist', contact_website: 'https://fliorens.com', contact_phone: null, contact_email: null, description: "Locally owned Sarasota florist founded by Liora offering garden-style custom floral design for weddings and events plus everyday bouquets and floral workshops.", specialties: ['wedding florals', 'garden-style design', 'floral workshops'], service_area: ['Sarasota'] },
  { name: 'Sarasota Fleurs', city: 'Sarasota', category: 'florist', contact_website: 'https://sarasotafleurs.com', contact_phone: '813-816-1134', contact_email: null, description: "Sarasota boutique floral design studio specializing in weddings, proposals, and curated events along the Gulf Coast. Each design is built around the venue, season, and couple.", specialties: ['wedding floristry', 'proposals', 'elopements', 'luxury faux arrangements'], service_area: ['Sarasota', 'Longboat Key', 'Lido Key'] },
  { name: 'Blooms By The Beach', city: 'Bradenton Beach', category: 'florist', contact_website: 'https://bloomsbythebeach.com', contact_phone: '941-778-2555', contact_email: null, description: "Anna Maria Island's premiere boutique florist on Gulf Drive North in Bradenton Beach offering bespoke wedding florals, daily delivery, and floral workshops.", specialties: ['wedding florals', 'bespoke custom designs', 'event rentals'], service_area: ['Anna Maria Island', 'Bradenton Beach', 'Longboat Key', 'Sarasota'] },
  { name: 'Eden Floral Creations', city: 'Bradenton', category: 'florist', contact_website: 'https://edenfloralcreations.com', contact_phone: '941-281-8373', contact_email: 'wecare@edenfloralcreations.com', description: "Small family-owned Bradenton florist on 3rd Ave NW led by head designer and owner Victoria. Sources independently of mainstream wire services.", specialties: ['wedding florals', 'custom arrangements', 'same-day local delivery'], service_area: ['Bradenton', 'Cortez', 'Palmetto'] },
  { name: 'A Slice of Heaven Custom Cakes', city: 'Lakewood Ranch', category: 'baker', contact_website: 'https://www.sarasotacakes.com', contact_phone: '941-341-0038', contact_email: 'Sarasotacakes@gmail.com', description: "Sarasota-area custom cake studio operating since 1997 from Lakewood Ranch Corporate Park, specializing in handcrafted buttercream wedding cakes. Markets as no-fondant, all-buttercream.", specialties: ['custom wedding cakes', 'buttercream-only design', 'drip cakes', '3-D designs'], service_area: ['Sarasota', 'Lakewood Ranch', 'Bradenton', 'Siesta Key'] },
  { name: 'Wonder Cake Creations', city: 'Sarasota', category: 'baker', contact_website: 'https://wondercakecreation.com', contact_phone: '941-315-8166', contact_email: null, description: "Sarasota custom cake shop on Boulevard of the Arts led by Master Cake Designer Moreli Hernandez G., creating custom wedding, anniversary, and specialty cakes.", specialties: ['custom wedding cakes', 'destination wedding cakes', 'specialty dietary cakes'], service_area: ['Sarasota', 'Bradenton', 'Siesta Key', 'Lakewood Ranch'] },
  { name: "Paisano's Italian Bakery", city: 'Sarasota', category: 'baker', contact_website: 'https://www.paisanositalianbakery.com', contact_phone: '941-926-8422', contact_email: null, description: "Independent Italian bakery on Stickney Point Road in Sarasota offering custom wedding cakes alongside cupcakes, cookies, biscotti, and Italian pastries.", specialties: ['custom wedding cakes', 'Italian pastries', 'cupcakes and cookies'], service_area: ['Sarasota'] },
  { name: 'Cakes by Ron', city: 'Sarasota', category: 'baker', contact_website: 'https://www.cakesbyron.com', contact_phone: '941-365-2991', contact_email: 'ron@cakesbyron.com', description: "Owner-operated Sarasota bakery on Fruitville Road run by Ron for over 25 years, specializing in luxury and resort wedding cakes.", specialties: ['luxury wedding cakes', 'resort weddings', 'custom cakes'], service_area: ['Sarasota'] },
  { name: 'Hometown Desserts', city: 'Anna Maria', category: 'baker', contact_website: 'https://www.hometowndesserts.com', contact_phone: '941-896-3167', contact_email: null, description: "Anna Maria Island custom dessert shop on Pine Avenue founded in 2007 by owner Cindy Tutterow. Known for the signature Key Lime Coconut cake plus custom wedding cakes.", specialties: ['custom wedding cakes', 'Key Lime Coconut cake', 'cheesecakes', 'pies'], service_area: ['Anna Maria Island', 'Bradenton'] },

  // ── SOUTHWEST FLORIDA (20) ──
  { name: 'SBS Weddings and Events', city: 'Naples', category: 'planner', contact_website: 'https://www.sbsweddings.com', contact_phone: '239-825-2514', contact_email: 'info@sbsweddings.com', description: "A Naples-based mother-daughter boutique planning firm focused on high-touch hospitality and seamlessly designed celebrations. Treats the planning process itself as memorable as the wedding day.", specialties: ['full-service planning', 'design', 'luxury weddings'], service_area: ['Naples', 'Marco Island', 'Bonita Springs'] },
  { name: "Lyane Mor' Events", city: 'Naples', category: 'planner', contact_website: 'https://lyanemor.com', contact_phone: null, contact_email: null, description: "A Naples wedding and event design studio specializing in elevated, design-forward celebrations. Explicitly limits client intake to provide personalized vision curation.", specialties: ['design-forward weddings', 'luxury planning', 'event design'], service_area: ['Naples', 'Southwest Florida'] },
  { name: 'Amber Jane Weddings', city: 'Naples', category: 'planner', contact_website: 'https://www.amberjaneweddings.com', contact_phone: null, contact_email: null, description: "Boutique SW Florida planner offering full-service, partial planning, and day-of coordination across Naples, Marco Island, Fort Myers, Sanibel, and Captiva. Owner Amber tailors packages.", specialties: ['full-service planning', 'partial planning', 'day-of coordination', 'micro weddings'], service_area: ['Naples', 'Marco Island', 'Fort Myers', 'Sanibel', 'Captiva'] },
  { name: 'Lexi and Co Weddings and Events', city: 'Naples', category: 'planner', contact_website: 'https://www.lexiandcoevents.com', contact_phone: '239-210-8293', contact_email: 'Hello@Lexiandcoevents.com', description: "Owner Lexi runs a boutique Naples and Fort Myers planning studio offering full-service design and execution alongside month-of coordination.", specialties: ['full-service design', 'month-of coordination'], service_area: ['Naples', 'Fort Myers'] },
  { name: 'Florida Wedding Design', city: 'Cape Coral', category: 'planner', contact_website: 'https://floridaweddingdesign.com', contact_phone: null, contact_email: null, description: "A Cape Coral-based boutique planning studio led by Brittiny offering full-service planning, design, and coordination across SW Florida.", specialties: ['full-service planning', 'design', 'coordination'], service_area: ['Cape Coral', 'Fort Myers', 'Naples', 'Sanibel', 'Marco Island'] },
  { name: 'Luminaire Foto', city: 'Naples', category: 'photographer', contact_website: 'https://www.luminairefoto.com', contact_phone: null, contact_email: null, description: "A Naples boutique photography studio led by Karl, specializing in personalized, intimate sessions for weddings, families, and editorial branding.", specialties: ['weddings', 'intimate sessions', 'editorial portraits'], service_area: ['Naples', 'Marco Island', 'Sanibel', 'Captiva'] },
  { name: "Miller's Photo and Film", city: 'Naples', category: 'photographer', contact_website: 'https://millersphotoandfilm.com', contact_phone: null, contact_email: null, description: "Naples husband-and-wife team Emma and Kowan deliver refined, emotion-driven wedding photography paired with cinematic, story-led films. Documented 200+ weddings.", specialties: ['wedding photography', 'wedding film', 'engagement portraits'], service_area: ['Naples', 'Fort Myers'] },
  { name: 'Maria Glassford Photography', city: 'Fort Myers', category: 'photographer', contact_website: 'https://mariaglassford.com', contact_phone: '239-218-3811', contact_email: 'maria@mariaglassford.com', description: "An SW Florida boutique photographer offering romantic, editorial, and lifestyle wedding coverage with a fine-art-meets-photojournalism approach.", specialties: ['editorial weddings', 'lifestyle', 'photojournalism'], service_area: ['Fort Myers', 'Naples', 'Sanibel', 'Captiva'] },
  { name: 'Lori Kelly Photography', city: 'Fort Myers', category: 'photographer', contact_website: 'https://www.lorikellysphotography.com', contact_phone: '239-699-2312', contact_email: 'lorikellyphotography@yahoo.com', description: "Fort Myers photographer Lori Kelly captures natural, timeless wedding imagery across SWFL backdrops from beaches to old-Florida farms.", specialties: ['weddings', 'seniors', 'family', 'natural light'], service_area: ['Fort Myers', 'Cape Coral', 'Sanibel', 'Captiva', 'Naples'] },
  { name: 'Sea Soul Studios', city: 'North Fort Myers', category: 'photographer', contact_website: 'https://seasoulstudios.com', contact_phone: '239-672-3056', contact_email: null, description: "Award-winning North Fort Myers studio led by Tamera McPherson, specializing in timeless, romantic wedding portraiture for the modern couple. Limits weddings booked per year.", specialties: ['wedding photography', 'engagement', 'aerial', 'beach'], service_area: ['Fort Myers', 'Cape Coral', 'Sanibel', 'Captiva', 'Bonita Springs', 'Naples'] },
  { name: 'Jardin Floral Design', city: 'Naples', category: 'florist', contact_website: 'https://jardinfdflowers.com', contact_phone: '239-404-1050', contact_email: 'info@jardinfloraldesign.com', description: "An independent Naples boutique florist on Tamiami Trail North providing meticulously crafted weddings and event florals across SW Florida. 300+ five-star reviews.", specialties: ['wedding florals', 'event florals', 'luxury arrangements'], service_area: ['Naples', 'Bonita Springs', 'Estero', 'Fort Myers'] },
  { name: 'Naples Picasso Flowers', city: 'Naples', category: 'florist', contact_website: 'https://naplespicassoflowers.com', contact_phone: '239-297-0352', contact_email: 'naplespicassoflowers@gmail.com', description: "An independent Old Naples 5th Avenue flower studio led by European Master Designer Mirela Benes, specializing in luxury wedding floral and ceremony installations.", specialties: ['luxury wedding florals', 'ceremony installations', 'event design'], service_area: ['Naples', 'Marco Island', 'Bonita Springs', 'Fort Myers'] },
  { name: "SuEllen's Floral Company", city: 'Cape Coral', category: 'florist', contact_website: 'https://suellensfloral.com', contact_phone: '239-574-4000', contact_email: 'suellensfloral@gmail.com', description: "An independent Cape Coral floral shop with 28+ years interpreting wedding visions across SW Florida. Multi-time WeddingWire Couples' Choice winner.", specialties: ['wedding florals', 'event arrangements', 'bridal bouquets'], service_area: ['Cape Coral', 'Fort Myers', 'Pine Island', 'Estero'] },
  { name: 'Floral Artistry of Sanibel', city: 'Estero', category: 'florist', contact_website: 'https://floralartistrystudios.com', contact_phone: '239-472-3040', contact_email: 'design@floralartistrystudios.com', description: "Independent boutique florist established 1997, serving Sanibel, Captiva, Estero, and Bonita Springs with custom wedding and event florals. After Hurricane Ian, the team relocated to Estero.", specialties: ['wedding florals', 'destination weddings', 'gala events'], service_area: ['Sanibel', 'Captiva', 'Estero', 'Bonita Springs', 'Fort Myers'] },
  { name: 'Madelaine Signature Flowers', city: 'Bonita Springs', category: 'florist', contact_website: 'https://www.madelainesignatureflowers.com', contact_phone: '239-221-7245', contact_email: null, description: "An independent Bonita Springs floral studio founded by Madelaine Ojeda offering tailored wedding and event design with quality blooms.", specialties: ['wedding bouquets', 'centerpieces', 'ceremony decor'], service_area: ['Bonita Springs', 'Estero', 'Naples'] },
  { name: 'Ema Sweets Boutique Cakes', city: 'Naples', category: 'baker', contact_website: 'https://www.emasweets.com', contact_phone: null, contact_email: null, description: "A Naples home-based boutique bakery making custom, made-to-order wedding cakes from scratch using fresh ingredients. Specializes in stunning, timeless designs.", specialties: ['custom wedding cakes', 'European-style cakes', 'gluten-free'], service_area: ['Naples', 'Southwest Florida'] },
  { name: 'Sweetified Bakery', city: 'Marco Island', category: 'baker', contact_website: 'https://www.sweetified.com', contact_phone: '239-201-2413', contact_email: 'lexie@sweetified.com', description: "Marco Island bakery led by owner-designer Lexie Verbruggen creating luxury wedding cakes with hand-piped detail, sculpted blooms, and metallic accents.", specialties: ['luxury wedding cakes', 'dessert spreads', 'hand-piped detail'], service_area: ['Marco Island', 'Naples'] },
  { name: 'Sassy Cakes of Naples', city: 'Naples', category: 'baker', contact_website: 'https://www.sassycakesnaples.com', contact_phone: '239-687-5100', contact_email: 'SassyCakesofNaples@gmail.com', description: "A Naples custom cake shop on Collier Center Way creating personalized wedding cakes plus cupcakes, cake pops, and Cake-Tinis for SW Florida couples.", specialties: ['custom wedding cakes', 'cupcakes', 'specialty desserts'], service_area: ['Naples', 'Bonita Springs', 'Estero', 'Marco Island', 'Fort Myers'] },
  { name: 'LadyCakes Bakery', city: 'Cape Coral', category: 'baker', contact_website: 'https://iloveladycakes.com', contact_phone: '239-549-2253', contact_email: 'orders@iloveladycakes.com', description: "A family-owned Cape Coral custom bakery founded in 2014 by Bess LadyCakes Charles, specializing in breathtaking wedding cakes and dessert tables.", specialties: ['custom wedding cakes', 'dessert tables', 'cupcakes'], service_area: ['Cape Coral', 'Fort Myers', 'Naples', 'Bonita Springs', 'Estero'] },
  { name: "Mikkelsen's Pastry Shop", city: 'Naples', category: 'baker', contact_website: 'https://mikkelsenspastryshop.com', contact_phone: '239-596-5996', contact_email: 'cakes@mikkelsenspastryshop.com', description: "An independent Naples pastry shop run by Paw and Elizabeth Mikkelsen since 2000, hand-crafting custom wedding cakes from scratch using fresh ingredients.", specialties: ['custom wedding cakes', 'specialty cakes', 'European pastries'], service_area: ['Naples', 'Marco Island', 'Bonita Springs'] },

  // ── NORTHEAST FLORIDA (20) ──
  { name: 'Kelsi Elizabeth Events', city: 'St. Augustine', category: 'planner', contact_website: 'https://www.kelsielizabethevents.com', contact_phone: '904-826-7123', contact_email: 'hello@kelsielizabethevents.com', description: "A boutique wedding and event planning company in historic St. Augustine. Owner Kelsi personally serves as planner, designer, and friend to every client.", specialties: ['full-service planning', 'design', 'boutique custom weddings'], service_area: ['St. Augustine', 'Jacksonville', 'North Florida'] },
  { name: 'Heather Hagin Events', city: 'Ponte Vedra Beach', category: 'planner', contact_website: 'https://www.heatherhaginevents.com', contact_phone: null, contact_email: null, description: "Ponte Vedra-based wedding and event planning studio offering tiered packages from month-of and day-of coordination through full-service planning.", specialties: ['full-service planning', 'month-of coordination', 'in-house decor'], service_area: ['Ponte Vedra', 'Jacksonville Beach', 'Amelia Island', 'St. Augustine'] },
  { name: 'Details Event Design', city: 'Fernandina Beach', category: 'planner', contact_website: 'https://www.detailseventdesign.com', contact_phone: '904-806-0101', contact_email: 'natalie@detailseventdesign.com', description: "A full-service wedding and event planning company located in Fernandina Beach, specializing in unique celebrations across Florida's First Coast. Lead planner Natalie.", specialties: ['full-service planning', 'event design', 'destination weddings'], service_area: ['Fernandina Beach', 'Amelia Island', 'Jacksonville'] },
  { name: 'Lulu Events Co', city: 'Jacksonville', category: 'planner', contact_website: 'https://luluevents.co', contact_phone: '786-208-7016', contact_email: 'info@luluevents.co', description: "A boutique wedding and event planning company founded in Jacksonville in 2020 by Vicki Blood. Focuses on meaningful celebrations rather than perfection.", specialties: ['full-service planning', 'destination weddings', 'event design', 'concierge'], service_area: ['Jacksonville', 'St. Augustine', 'Amelia Island'] },
  { name: 'Amelia Island Weddings', city: 'Amelia Island', category: 'planner', contact_website: 'https://ameliaislandweddings.com', contact_phone: '904-206-3115', contact_email: null, description: "Owner Lisa Presnell's full-service planning company specializing in coastal celebrations on Amelia Island. 25+ years of local event-planning experience.", specialties: ['beach weddings', 'elopements', 'officiant services', 'vow renewals'], service_area: ['Amelia Island', 'Fernandina Beach', 'Northeast Florida coast'] },
  { name: 'Monarch Studio', city: 'St. Augustine', category: 'photographer', contact_website: 'https://www.themonarchwedding.com', contact_phone: '904-516-8203', contact_email: 'studio@themonarchstudio.com', description: "A full-service wedding photography studio located on U.S. 1 in St. Augustine. Focuses on classic, elegant, and timeless imagery.", specialties: ['timeless wedding photography', 'engagements', 'elopements'], service_area: ['St. Augustine', 'Northeast Florida'] },
  { name: 'Sarah Hedden Photography', city: 'Jacksonville', category: 'photographer', contact_website: 'https://sarahheddenphotography.com', contact_phone: null, contact_email: 'sarah@sarahhedden.com', description: "A Jacksonville-based luxury photography studio in the San Marco neighborhood, in business since 2011. Six times named Best Jacksonville Photographer.", specialties: ['luxury wedding photography', 'fine-art editorial', 'maternity'], service_area: ['Jacksonville', 'St. Augustine', 'Amelia Island'] },
  { name: 'Lisa Silva Photography', city: 'Ponte Vedra Beach', category: 'photographer', contact_website: 'https://www.lisasilvaphoto.com', contact_phone: '850-284-2934', contact_email: 'lisa@lisasilvaphoto.com', description: "An award-winning fine-art film wedding photographer based in Ponte Vedra Beach. Featured in Style Me Pretty and Martha Stewart Weddings.", specialties: ['fine-art film', 'luxury weddings', 'destination weddings'], service_area: ['Ponte Vedra Beach', 'Jacksonville', 'St. Augustine'] },
  { name: 'Jensen Bell Photography', city: 'Amelia Island', category: 'photographer', contact_website: 'https://www.jensenbellphotography.com', contact_phone: '904-557-1818', contact_email: null, description: "An Amelia Island and Fernandina Beach photographer specializing in weddings, couples, and family portraits.", specialties: ['weddings', 'engagements', 'beach portraits', 'family'], service_area: ['Amelia Island', 'Fernandina Beach', 'Northeast Florida'] },
  { name: 'Page Teahan Photography', city: 'Amelia Island', category: 'photographer', contact_website: 'https://www.pageteahan.com', contact_phone: null, contact_email: null, description: "A Northeast Florida wedding and family photographer based on Amelia Island. Captures couples, weddings, families, and maternity sessions.", specialties: ['weddings', 'couples', 'families', 'maternity'], service_area: ['Amelia Island', 'Fernandina Beach', 'Northeast Florida'] },
  { name: 'Jade Violet Wedding Floral', city: 'St. Augustine', category: 'florist', contact_website: 'https://jadevioletweddingfloral.com', contact_phone: '904-415-2480', contact_email: 'jadevioletweddingfloral333@gmail.com', description: "A St. Augustine boutique florist on A1A South specializing in custom bridal bouquets, centerpieces, ceremony decor, corsages, and boutonnieres.", specialties: ['bridal bouquets', 'ceremony decor', 'centerpieces', 'wedding-only'], service_area: ['St. Augustine', 'Northeast Florida'] },
  { name: 'Tula Rose Floral and Event Design', city: 'St. Augustine', category: 'florist', contact_website: 'https://tularoseevents.com', contact_phone: '904-599-5970', contact_email: 'info@tularoseevents.com', description: "A full-service floral and event design studio in St. Augustine led by Tessa, specializing in upscale wedding florals from elegant to boho aesthetics.", specialties: ['wedding florals', 'event design', 'installations'], service_area: ['St. Augustine', 'Northeast Florida'] },
  { name: 'Liz Stewart Floral Design', city: 'Jacksonville Beach', category: 'florist', contact_website: 'https://www.lizflowers.com', contact_phone: '904-246-0016', contact_email: 'info@lizflowers.com', description: "An award-winning boutique studio on Third Street South in Jacksonville Beach. Known for vibrant arrangements, bridal bouquets, floral arches, and event installations.", specialties: ['bridal bouquets', 'floral installations', 'arches'], service_area: ['Jacksonville Beach', 'Jacksonville', 'Ponte Vedra'] },
  { name: 'The Heirloom Yard', city: 'Amelia Island', category: 'florist', contact_website: 'https://www.theheirloomyard.com', contact_phone: '904-844-2861', contact_email: 'hello@theheirloomyard.com', description: "A seasonal, garden-inspired wedding floral studio based on Amelia Island serving Northeast Florida and coastal Georgia. Limits annual events.", specialties: ['garden-style florals', 'seasonal design', 'destination weddings'], service_area: ['Amelia Island', 'Fernandina Beach', 'Northeast Florida'] },
  { name: 'Fleurs De Vedra', city: 'Ponte Vedra Beach', category: 'florist', contact_website: 'https://www.fleursdevedra.com', contact_phone: '904-373-8640', contact_email: 'kristina@fleursdevedra.com', description: "An AIFD-accredited floral and event design company in Ponte Vedra Beach owned by designer Kristina. Specializes in custom wedding and event arrangements.", specialties: ['custom wedding florals', 'paper flower installations', 'event design'], service_area: ['Ponte Vedra Beach', 'Jacksonville', 'St. Augustine'] },
  { name: "Sweet Tiffany's", city: 'Saint Johns', category: 'baker', contact_website: 'https://sweettiffanys.net', contact_phone: '770-519-8504', contact_email: null, description: "An elite cake studio in the St. Johns / St. Augustine area led by Chef Tiffany Adams, who combines 28 years as a food scientist, pastry chef, and cake designer.", specialties: ['custom wedding cakes', "groom's cakes", 'epicurean pastries', 'allergy-friendly'], service_area: ['St. Johns', 'St. Augustine', 'Jacksonville'] },
  { name: "LuLi's Bakery", city: 'St. Augustine', category: 'baker', contact_website: 'https://www.luliscupcakes.com', contact_phone: '904-824-5280', contact_email: 'luliscupcakessta@gmail.com', description: "A 17-year-old neighborhood St. Augustine bakery on San Marco Avenue specializing in custom wedding cakes, cupcakes, cupcake bouquets, and gluten-free or vegan options.", specialties: ['custom wedding cakes', 'cupcakes', 'gluten-free', 'vegan'], service_area: ['St. Augustine', 'Palm Coast', 'Jacksonville'] },
  { name: 'Filigree Cake Design', city: 'Jacksonville', category: 'baker', contact_website: 'https://www.filigreecakedesign.com', contact_phone: '904-864-5268', contact_email: 'info@filigreecakedesign.com', description: "A Jacksonville custom cake studio led by designer Niki Viczian, specializing in elegant wedding and celebration cakes. Top 10 Wedding Cake Bakers in Jacksonville.", specialties: ['custom wedding cakes', 'celebration cakes', 'premium design'], service_area: ['Jacksonville', 'Northeast Florida'] },
  { name: 'Cake and Cookie Art by Janine', city: 'Saint Johns', category: 'baker', contact_website: 'https://www.cakeandcookieart.com', contact_phone: '904-563-0704', contact_email: 'CakeandCookieArt@yahoo.com', description: "An owner-operated custom bakery in Julington Creek Plantation, St. Johns, serving the greater Jacksonville and St. Augustine areas.", specialties: ['custom wedding cakes', 'decorated cookies', 'cupcakes'], service_area: ['Jacksonville', 'St. Johns', 'Ponte Vedra', 'St. Augustine'] },
  { name: "Nana Teresa's Bake Shop", city: 'Fernandina Beach', category: 'baker', contact_website: 'https://nanateresa.com', contact_phone: '904-277-7977', contact_email: null, description: "A 3rd Street bakery in historic downtown Fernandina Beach specializing in custom wedding cakes, celebration cakes, and fresh-baked breakfast goods.", specialties: ['custom wedding cakes', 'celebration cakes', 'fresh-baked goods'], service_area: ['Fernandina Beach', 'Amelia Island'] },

  // ── CENTRAL FLORIDA (20) ──
  { name: 'Blush by Brandee Gaar', city: 'Orlando', category: 'planner', contact_website: 'https://blushbbg.com', contact_phone: null, contact_email: 'weddings@blushbbg.com', description: "An owner-led boutique wedding and event planning studio focused on bespoke, stress-free celebrations. Founder Brandee Gaar leads a small named team since 2007.", specialties: ['full-service planning', 'day-of coordination', 'destination weddings'], service_area: ['Orlando', 'St. Augustine', 'Central Florida'] },
  { name: 'Bella Sposa Events', city: 'Orlando', category: 'planner', contact_website: 'https://bellasposaevents.com', contact_phone: null, contact_email: null, description: "An owner-founded Orlando wedding planning boutique established in 2016 by Jennifer Lopez, who brings an interior-design background to wedding curation.", specialties: ['wedding planning', 'event design', 'intimate celebrations'], service_area: ['Orlando', 'Central Florida'] },
  { name: 'Winter Park Wedding Company', city: 'Winter Park', category: 'planner', contact_website: 'https://www.winterparkweddingcompany.com', contact_phone: '407-539-1538', contact_email: 'suzanne@winterparkweddingcompany.com', description: "A boutique Winter Park-based planning company specializing in Downtown Winter Park venues including Kraft Azalea Gardens, Capen House, and the Winter Park Wedding Chapel.", specialties: ['Winter Park venue weddings', 'full coordination', 'garden ceremonies'], service_area: ['Winter Park', 'Orlando', 'Central Florida'] },
  { name: 'L3 Events', city: 'Sanford', category: 'planner', contact_website: 'https://l3events.com', contact_phone: '407-497-6400', contact_email: null, description: "Master Certified Wedding Planner Rebecca Lang's boutique firm serving Central Florida from Sanford and Orlando since 2018. Offers month-of, partial, and full-service collections.", specialties: ['month-of coordination', 'partial planning', 'full-service planning'], service_area: ['Sanford', 'Lake Mary', 'Orlando', 'Central Florida'] },
  { name: 'Yasmen Katrina Events', city: 'Kissimmee', category: 'planner', contact_website: 'https://www.ykweddingsevents.com', contact_phone: null, contact_email: null, description: "A Central Florida wedding and event planning boutique designed for romantic couples who want polish without the stress. Tiered offerings from day-of to full planning.", specialties: ['day-of coordination', 'full planning', 'wedding design'], service_area: ['Kissimmee', 'Orlando', 'Central Florida'] },
  { name: 'Mary Fosky Photography', city: 'Orlando', category: 'photographer', contact_website: 'https://maryfoskyphotography.com', contact_phone: '407-782-8228', contact_email: 'mrsfosky@gmail.com', description: "Owner-shot Orlando boutique studio capturing weddings in a distinct, organic, film-influenced style with a deliberately limited annual booking calendar.", specialties: ['film-influenced wedding photography', 'engagements', 'elopements', 'custom wedding albums'], service_area: ['Orlando', 'Central Florida'] },
  { name: 'Jennifer Holly Photography', city: 'Orlando', category: 'photographer', contact_website: 'https://jenniferholly.co', contact_phone: null, contact_email: null, description: "A solo Orlando wedding photographer with a light-and-airy, editorial style aimed at hopeless romantics. Emphasizes connection-based, organic imagery.", specialties: ['light and airy', 'editorial', 'engagements', 'couples'], service_area: ['Orlando', 'Central Florida'] },
  { name: 'Cherise Takes Pictures', city: 'Winter Park', category: 'photographer', contact_website: 'https://www.cherisetakespictures.com', contact_phone: '321-328-5652', contact_email: 'hello@mynameischerise.com', description: "Cherise Adams' Winter Park-based wedding and portrait studio with 15+ years behind the camera. Storytelling-focused, LGBTQ+-friendly.", specialties: ['wedding photography', 'engagements', 'LGBTQ+ couples', 'portraits'], service_area: ['Winter Park', 'Orlando', 'Central Florida'] },
  { name: 'Sierra Ford Photography', city: 'Mount Dora', category: 'photographer', contact_website: 'https://sierraford.com', contact_phone: null, contact_email: null, description: "Sierra Ford runs a boutique photography studio out of Mount Dora serving elopements, weddings, family, and brand portrait work in Central Florida.", specialties: ['elopements', 'weddings', 'branding', 'portraits'], service_area: ['Mount Dora', 'Orlando', 'Central Florida'] },
  { name: 'Bonnie Whicher Photography', city: 'Mount Dora', category: 'photographer', contact_website: 'https://bonniewhicherphotography.com', contact_phone: '352-638-5967', contact_email: null, description: "A husband-and-wife studio with 25 years of experience and a 1,700 sq ft Mount Dora facility stocked with hundreds of backdrops and props.", specialties: ['weddings', 'engagements', 'family portraits', 'studio shoots'], service_area: ['Mount Dora', 'Lake County', 'Central Florida'] },
  { name: 'Ashley Jane Photography', city: 'Sanford', category: 'photographer', contact_website: 'https://ashleyjane-photography.com', contact_phone: '563-528-1152', contact_email: 'ashley@ashleyjane-photography.com', description: "Husband-and-wife team Ashley and Jacob Van Zandt operating a boutique studio at 301 W. 7th St in historic Downtown Sanford.", specialties: ['wedding photography', 'engagements', 'boudoir', 'branding portraits'], service_area: ['Sanford', 'Orlando', 'Winter Park'] },
  { name: 'Dream Designs Florist', city: 'Orlando', category: 'florist', contact_website: 'https://dreamdesignsflorist.com', contact_phone: '407-896-1199', contact_email: 'info@dreamdesignsflorist.com', description: "A home-based Orlando floral studio led by Danielle with 25+ years of wedding floral experience and Knot Hall of Fame credentials.", specialties: ['bridal bouquets', 'ceremony arches', 'reception centerpieces', 'cake flowers'], service_area: ['Orange', 'Osceola', 'Seminole', 'Volusia'] },
  { name: 'Bluegrass Chic Floral', city: 'Orlando', category: 'florist', contact_website: 'https://bluegrasschic.com', contact_phone: '407-900-3515', contact_email: 'info@bluegrasschic.com', description: "An independent full-service Orlando wedding and event floral design house at 2815 Directors Row. Offers eight signature design styles.", specialties: ['ceremony installations', 'ceiling florals', 'tablescapes', 'rentals'], service_area: ['Orlando', 'Central Florida'] },
  { name: 'Bloomed and Rooted', city: 'Winter Park', category: 'florist', contact_website: 'https://www.bloomedandrooted.com', contact_phone: null, contact_email: null, description: "A faith-inspired floral and design boutique run by Rachel, serving Winter Park and Orlando weddings and corporate events.", specialties: ['modern wedding floral', 'acrylic signage', 'ceremony design', 'event styling'], service_area: ['Winter Park', 'Orlando', 'Central Florida'] },
  { name: 'Atmospheres of Winter Park', city: 'Winter Park', category: 'florist', contact_website: 'https://www.atmospheresofwinterpark.com', contact_phone: null, contact_email: null, description: "A luxury floral design boutique at 2121 W. Fairbanks Ave in Winter Park led by Master Designer John Taylor.", specialties: ['luxury wedding floral', 'ceremony installations', 'corporate events'], service_area: ['Winter Park', 'Orlando', 'Central Florida'] },
  { name: "Claudia's Pearl Florist", city: 'Mount Dora', category: 'florist', contact_website: 'https://www.claudiaspearlflorist.com', contact_phone: null, contact_email: null, description: "A family-owned Mount Dora boutique florist with 35+ years designing weddings and special events. Daily delivery across Lake County.", specialties: ['bridal bouquets', 'ceremony florals', 'reception centerpieces'], service_area: ['Mount Dora', 'Lake County', 'Central Florida'] },
  { name: 'Petals by Design', city: 'Orlando', category: 'florist', contact_website: 'https://petalsorlando.com', contact_phone: null, contact_email: 'info@petalsorlando.com', description: "Mother-daughter team Tracy Ferguson and Brittany Dowda have crafted Central Florida wedding florals since 2007.", specialties: ['bridal bouquets', 'boutonnieres', 'centerpieces', 'ceremony florals'], service_area: ['Orlando', 'Winter Park', 'Lake Mary'] },
  { name: 'Sprinkles Custom Cakes', city: 'Winter Park', category: 'baker', contact_website: 'https://sprinklescakes.net', contact_phone: null, contact_email: null, description: "Established 1989, a Winter Park boutique cake studio specializing in wedding and custom cakes for Central Florida couples. Appointment-only.", specialties: ['wedding cakes', 'custom celebration cakes', 'tiered designs'], service_area: ['Winter Park', 'Orlando', 'Central Florida'] },
  { name: 'Le Petit Sweet', city: 'Mount Dora', category: 'baker', contact_website: 'https://www.lepetitsweet.com', contact_phone: '352-729-2453', contact_email: 'info@lepetitsweet.com', description: "Brittany Baker's Mount Dora bakery at 110 W 5th Ave designs custom wedding cakes ranging from rustic buttercream to highly detailed fondant.", specialties: ['custom wedding cakes', 'fondant designs', 'sugar flowers', 'dessert tables'], service_area: ['Mount Dora', 'Lake County', 'Central Florida'] },
  { name: "Lina's Cakes by Design", city: 'Sanford', category: 'baker', contact_website: 'https://www.linascakesbydesign.com', contact_phone: '386-561-8037', contact_email: 'linascakesbydesign@gmail.com', description: "Owner-baker Lina runs a Sanford bespoke cake studio specializing in luxurious wedding cake designs made from scratch.", specialties: ['bespoke wedding cakes', 'tasting consultations', 'tiered designs'], service_area: ['Sanford', 'Lake Mary', 'Central Florida'] },

  // ── PANHANDLE (20) ──
  { name: 'Kiss The Bride Weddings', city: 'Miramar Beach', category: 'planner', contact_website: 'https://kissthebridedestin.com', contact_phone: '850-376-8272', contact_email: 'kristi@kissthebrideweddings.com', description: "An award-winning 30A wedding planning company led by Certified Wedding Planner Kristi Purvis. Specializes in destination celebrations along Highway 30A with 14+ years of experience.", specialties: ['full-service planning', 'destination weddings', '30A beach weddings'], service_area: ['Rosemary Beach', 'Seaside', 'WaterColor', 'Alys Beach', 'Destin'] },
  { name: 'The Eventful Planner', city: 'Destin', category: 'planner', contact_website: 'https://www.theeventfulplanner.com', contact_phone: '850-460-4023', contact_email: 'tammy@theeventfulplanner.com', description: "A full-service event planning and catering boutique founded in 2005 by owner Tammy D'Agostino. Nestled among the coastal communities of Destin and 30A.", specialties: ['luxury full-service planning', 'in-house catering', 'design and layout'], service_area: ['Destin', '30A', 'Seaside', 'Seagrove'] },
  { name: 'Fancy Events', city: 'Santa Rosa Beach', category: 'planner', contact_website: 'https://yourfancyevent.com', contact_phone: '850-685-4472', contact_email: 'info@yourfancyevent.com', description: "A boutique full-service wedding planning and design firm led by Jamie Cooper with 13+ years of experience. Personalized design and effortless elegance.", specialties: ['full-service planning', 'design', 'destination weddings'], service_area: ['Santa Rosa Beach', '30A', 'Destin'] },
  { name: 'Destin To Wed Event Planning', city: 'Destin', category: 'planner', contact_website: 'https://www.destintowed.com', contact_phone: '850-687-0076', contact_email: 'Sherri@destintowed.com', description: "A boutique luxury planning firm owned by lead planner Sherri Kuhn. Limits annual client roster to ensure dedicated, high-touch service.", specialties: ['luxury destination weddings', 'full planning', 'partial planning'], service_area: ['Destin', '30A', 'Emerald Coast'] },
  { name: 'Southern Frills Weddings and Events', city: 'Pensacola', category: 'planner', contact_website: 'https://www.southernfrillsevents.com', contact_phone: '850-382-2448', contact_email: 'Kelly@southernfrillsevents.com', description: "A boutique wedding planning and design studio serving the Gulf Coast. Combines planning with design expertise.", specialties: ['full planning + design', 'month-of coordination', 'Gulf Coast weddings'], service_area: ['Pensacola', 'Pensacola Beach', 'Perdido Key'] },
  { name: 'Pure7 Studios', city: 'Santa Rosa Beach', category: 'photographer', contact_website: 'https://pure7studios.com', contact_phone: null, contact_email: null, description: "Family-owned photography studio operated by husband-and-wife team Ryan and Erica Manthey. Recognized as a leading 30A photographer.", specialties: ['wedding photography', 'engagement', '30A beach portraits', 'branding'], service_area: ['Santa Rosa Beach', 'Seaside', 'Rosemary Beach', 'Alys Beach', 'WaterColor', 'Destin'] },
  { name: 'Jessie Barksdale Photography', city: 'Rosemary Beach', category: 'photographer', contact_website: 'https://jessiebarksdale.com', contact_phone: null, contact_email: null, description: "A solo-owner luxury fine art wedding and family photographer based in Rosemary Beach with over a decade of experience.", specialties: ['luxury fine art weddings', 'destination weddings', 'Rosemary Beach', 'family portraits'], service_area: ['Rosemary Beach', 'Seaside', 'Alys Beach', 'Santa Rosa Beach', 'Destin'] },
  { name: 'Erika Dame Photography', city: 'Santa Rosa Beach', category: 'photographer', contact_website: 'https://erikadame.com', contact_phone: null, contact_email: 'erika@erikadame.com', description: "A two-photographer team based on 30A capturing wedding celebrations through a documentary approach and a thoughtful, steady presence.", specialties: ['documentary wedding photography', 'timeless aesthetic', 'destination weddings'], service_area: ['30A', 'Pensacola'] },
  { name: 'Weddings by Adina', city: 'Destin', category: 'photographer', contact_website: 'https://weddingsbyadina.com', contact_phone: null, contact_email: 'weddingsbyadina@gmail.com', description: "An award-winning fine-art wedding and portrait photographer Adina Preston, with 14+ years of experience. Blends photojournalistic, editorial, and light-and-airy styles.", specialties: ['fine-art weddings', 'elopements', 'editorial portraits'], service_area: ['Destin', '30A', 'Rosemary Beach', 'Pensacola'] },
  { name: 'Stephen Teekell Photography', city: 'Port St. Joe', category: 'photographer', contact_website: 'https://www.stephenteekellphotography.com', contact_phone: '325-899-2440', contact_email: 'stphotos21@gmail.com', description: "An award-winning lifestyle photographer based in Port St. Joe specializing in candid, documentary-style wedding photography across the Forgotten Coast.", specialties: ['documentary weddings', 'Cape San Blas elopements', 'lifestyle portraits'], service_area: ['Port St. Joe', 'Cape San Blas', 'Mexico Beach', 'Indian Pass'] },
  { name: 'Bella Flora 30A', city: 'Santa Rosa Beach', category: 'florist', contact_website: 'https://bellaflora30a.com', contact_phone: null, contact_email: null, description: "An independent local floral studio in Santa Rosa Beach offering custom wedding design, fresh-flower delivery, and event styling along 30A.", specialties: ['wedding floral design', 'event styling', 'wedding rentals'], service_area: ['Santa Rosa Beach', 'Destin', 'Miramar Beach', 'Rosemary Beach'] },
  { name: 'Bloom Flower Artistry', city: 'Seaside', category: 'florist', contact_website: 'https://www.artistryinbloom.com', contact_phone: null, contact_email: 'florals@artistryinbloom.com', description: "A boutique floral design studio on Scenic 30A founded by Christy Calhoun. Focused on personalized collaboration with brides.", specialties: ['bridal bouquets', 'ceremony installations', 'centerpieces'], service_area: ['Seaside', 'Santa Rosa Beach', '30A corridor'] },
  { name: 'Couture Florals and Events', city: 'Destin', category: 'florist', contact_website: 'https://www.couturefloralsdesign.com', contact_phone: null, contact_email: null, description: "An innovative full-service floral and event design studio specializing in weddings across the Emerald Coast. Personalized consultations and inspiration boards.", specialties: ['wedding floral design', 'bespoke installations', 'venue styling'], service_area: ['Destin', 'Sandestin', '30A', 'Pensacola'] },
  { name: 'Fiore of Pensacola', city: 'Pensacola', category: 'florist', contact_website: 'https://www.fioreofpensacola.com', contact_phone: '850-469-1930', contact_email: null, description: "A full-service florist and boutique specializing in weddings and events in downtown Pensacola. Recognized by Style Me Pretty and Southern Living.", specialties: ['weddings', 'event floral design', 'destination brides'], service_area: ['Pensacola', 'Pensacola Beach', 'Perdido Key'] },
  { name: 'Sassy Sunflower', city: 'Apalachicola', category: 'florist', contact_website: 'https://www.sassysunflower.net', contact_phone: '850-653-6335', contact_email: null, description: "An independent full-service florist on Market Street in historic Apalachicola providing wedding bouquets, ceremony and reception flowers across the Forgotten Coast.", specialties: ['wedding bouquets', 'ceremony flowers', 'reception arrangements'], service_area: ['Apalachicola', 'Eastpoint', 'St. George Island', 'Cape San Blas'] },
  { name: 'Bonne Vie Specialty Custom Cakes', city: 'Santa Rosa Beach', category: 'baker', contact_website: 'http://www.bonneviespecialtyfoods.com', contact_phone: null, contact_email: null, description: "A boutique cakery owned by April Dixon (originally from New Orleans) specializing in custom, bespoke wedding and celebration cakes.", specialties: ['custom wedding cakes', 'bespoke design', 'celebration desserts'], service_area: ['Destin', 'Santa Rosa Beach', '30A'] },
  { name: "Sweet Henrietta's", city: 'Inlet Beach', category: 'baker', contact_website: 'https://www.sweethenriettas.com', contact_phone: null, contact_email: 'debbie@sweethenriettas.com', description: "A local custom bakery in WaterSound Town Center specializing in wedding cakes, cupcakes, and desserts baked with the finest ingredients.", specialties: ['custom wedding cakes', 'cupcakes', 'specialty desserts'], service_area: ['30A', 'Miramar Beach', 'Inlet Beach', 'WaterSound'] },
  { name: 'Sweetly Sisters', city: 'Santa Rosa Beach', category: 'baker', contact_website: 'https://www.sweetlysisters.com', contact_phone: null, contact_email: null, description: "A boutique cottage-food bakery run by family team Jessica, Daniel, and Michelle, baking classic Southern cakes with a dash of whimsy.", specialties: ['custom wedding cakes', "groom's cakes", 'Southern-style desserts'], service_area: ['Santa Rosa Beach', '30A', 'Destin'] },
  { name: 'Wade Cakes and Weddings', city: 'Pensacola', category: 'baker', contact_website: 'http://www.wadecakesandweddings.com', contact_phone: null, contact_email: null, description: "A boutique wedding bakery founded by head baker Latoya, specializing in bespoke designs for weddings, baby showers, vow renewals, and engagement parties.", specialties: ['custom wedding cakes', 'bespoke design', 'showers and vow renewals'], service_area: ['Pensacola', 'Pensacola Beach', 'Mobile', 'Fort Walton'] },
  { name: 'Forgotten Coast Cakes', city: 'Apalachicola', category: 'baker', contact_website: 'https://forgottencoastcakes.com', contact_phone: '850-368-5906', contact_email: null, description: "An at-home cottage-food bakery serving the Forgotten Coast with custom wedding, birthday, and special-occasion cakes and cupcakes.", specialties: ['custom wedding cakes', 'cupcakes', 'Forgotten Coast deliveries'], service_area: ['Apalachicola', 'Eastpoint', 'St. George Island', 'Cape San Blas'] },
];

function slugify(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/'/g, '')
    .replace(/[.,'"`/\\]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function synthesizeEmail(name: string): string {
  const slug = slugify(name);
  return `info@${slug}.com`;
}

async function main() {
  const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { persistSession: false },
  });

  console.log(`Inserting ${VENDORS.length} vendors…`);

  const rows = VENDORS.map((v) => {
    const slug = `${slugify(v.name)}-${slugify(v.city)}`;
    const email_real = !!v.contact_email;
    return {
      legacy_id: slug,
      slug,
      name: v.name,
      description: v.description,
      category: v.category,
      city: v.city,
      state: 'FL',
      service_area: v.service_area,
      specialties: v.specialties,
      tags: [],
      images: [],
      contact_phone: v.contact_phone,
      contact_email: v.contact_email ?? synthesizeEmail(v.name),
      contact_email_real: email_real,
      contact_website: v.contact_website,
      social_media: null,
    };
  });

  const { data, error } = await supabase
    .from('vendors')
    .upsert(rows, { onConflict: 'slug' })
    .select('slug, name, city, category');

  if (error) {
    console.error('Insert failed:', error);
    process.exit(1);
  }

  console.log(`✓ ${data?.length ?? 0} vendors upserted`);
  console.log('\nSlugs (for watercolor batch):');
  for (const v of data ?? []) console.log(`  ${v.slug}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
