
// Google Maps Venue Closure Verification Script
// This script helps systematically check each venue for closure status

const venues = [
  {
    "id": 1,
    "name": "Hialeah Park Racing & Casino",
    "city": "Hialeah",
    "state": "FL",
    "address": "100 E 32nd St, Hialeah, FL 33013",
    "phone": "N/A",
    "website": "https://hialeahparkcasino.com/events",
    "googleMapsQuery": "Hialeah Park Racing & Casino Hialeah FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hialeah%20Park%20Racing%20%26%20Casino%20Hialeah%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hialeah%20Park%20Racing%20%26%20Casino%20Hialeah%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 2,
    "name": "The Surfcomber Hotel",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.kimptonsurfcomber.com/",
    "googleMapsQuery": "The Surfcomber Hotel Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Surfcomber%20Hotel%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Surfcomber%20Hotel%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 3,
    "name": "MB Hotel",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.wyndhamhotels.com/trademark/miami-beach-florida/mb-hotel-trademark-collection/overview",
    "googleMapsQuery": "MB Hotel Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/MB%20Hotel%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=MB%20Hotel%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 4,
    "name": "Sea Watch on the Ocean",
    "city": "Broward",
    "state": "FL",
    "address": "Fort Lauderdale, Broward",
    "phone": "N/A",
    "website": "https://www.seawatchontheocean.com/",
    "googleMapsQuery": "Sea Watch on the Ocean Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sea%20Watch%20on%20the%20Ocean%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sea%20Watch%20on%20the%20Ocean%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 5,
    "name": "Emeril Lagasse Foundation Innovation Kitchen",
    "city": "Broward",
    "state": "FL",
    "address": "Sunrise, Broward",
    "phone": "N/A",
    "website": "https://www.arcculinary.com/innovation-kitchen",
    "googleMapsQuery": "Emeril Lagasse Foundation Innovation Kitchen Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Emeril%20Lagasse%20Foundation%20Innovation%20Kitchen%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Emeril%20Lagasse%20Foundation%20Innovation%20Kitchen%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 6,
    "name": "Coastal Yacht Charters",
    "city": "Broward",
    "state": "FL",
    "address": "Fort Lauderdale, Broward",
    "phone": "N/A",
    "website": "https://www.coastalyachtcharters.com/",
    "googleMapsQuery": "Coastal Yacht Charters Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Coastal%20Yacht%20Charters%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Coastal%20Yacht%20Charters%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 7,
    "name": "Vizcaya Museum & Gardens",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coconut Grove, Miami-Dade",
    "phone": "N/A",
    "website": "https://vizcaya.org/weddings-celebrations/",
    "googleMapsQuery": "Vizcaya Museum & Gardens Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Vizcaya%20Museum%20%26%20Gardens%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Vizcaya%20Museum%20%26%20Gardens%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 8,
    "name": "Ancient Spanish Monastery",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "North Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.spanishmonastery.com/",
    "googleMapsQuery": "Ancient Spanish Monastery Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Ancient%20Spanish%20Monastery%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Ancient%20Spanish%20Monastery%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 9,
    "name": "The Cooper Estate",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Redland, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.thecooperestate.com/",
    "googleMapsQuery": "The Cooper Estate Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Cooper%20Estate%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Cooper%20Estate%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 10,
    "name": "Curtiss Mansion",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Springs, Miami-Dade",
    "phone": "N/A",
    "website": "https://curtissmansion.org/",
    "googleMapsQuery": "Curtiss Mansion Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Curtiss%20Mansion%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Curtiss%20Mansion%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 11,
    "name": "Thalatta Estate",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Palmetto Bay, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.palmettobay-fl.gov/457/Thalatta-Estate",
    "googleMapsQuery": "Thalatta Estate Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Thalatta%20Estate%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Thalatta%20Estate%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 12,
    "name": "Deering Estate",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Cutler Bay, Miami-Dade",
    "phone": "N/A",
    "website": "https://deeringestate.org/event-rentals/",
    "googleMapsQuery": "Deering Estate Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Deering%20Estate%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Deering%20Estate%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 13,
    "name": "Fairchild Tropical Botanic Garden",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coral Gables, Miami-Dade",
    "phone": "N/A",
    "website": "https://fairchildgarden.org/private-events-and-weddings/",
    "googleMapsQuery": "Fairchild Tropical Botanic Garden Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Fairchild%20Tropical%20Botanic%20Garden%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Fairchild%20Tropical%20Botanic%20Garden%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 14,
    "name": "Historic Walton House",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Redland, Miami-Dade",
    "phone": "N/A",
    "website": "https://waltonhouse.com/",
    "googleMapsQuery": "Historic Walton House Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Historic%20Walton%20House%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Historic%20Walton%20House%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 15,
    "name": "Woman's Club of Coconut Grove",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coconut Grove, Miami-Dade",
    "phone": "N/A",
    "website": "https://womansclubofcoconutgrove.com/",
    "googleMapsQuery": "Woman's Club of Coconut Grove Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Woman's%20Club%20of%20Coconut%20Grove%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Woman's%20Club%20of%20Coconut%20Grove%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 16,
    "name": "The Bath Club",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.thebathclub.com/",
    "googleMapsQuery": "The Bath Club Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Bath%20Club%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Bath%20Club%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 17,
    "name": "The Cruz Building",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coconut Grove, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.cruzbuildings.com/",
    "googleMapsQuery": "The Cruz Building Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Cruz%20Building%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Cruz%20Building%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 18,
    "name": "Rusty Pelican",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Key Biscayne, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.therustypelican.com/private-events-miami/",
    "googleMapsQuery": "Rusty Pelican Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Rusty%20Pelican%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Rusty%20Pelican%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 19,
    "name": "Briza on the Bay",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Downtown Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.brizaonthebay.com/",
    "googleMapsQuery": "Briza on the Bay Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Briza%20on%20the%20Bay%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Briza%20on%20the%20Bay%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 20,
    "name": "Penthouse at Riverside Wharf",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Downtown Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://penthouserw.com/",
    "googleMapsQuery": "Penthouse at Riverside Wharf Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Penthouse%20at%20Riverside%20Wharf%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Penthouse%20at%20Riverside%20Wharf%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 21,
    "name": "Signature Grand",
    "city": "Broward",
    "state": "FL",
    "address": "Davie, Broward",
    "phone": "N/A",
    "website": "https://www.thesignaturegrand.com/",
    "googleMapsQuery": "Signature Grand Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Signature%20Grand%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Signature%20Grand%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 22,
    "name": "Jacaranda Country Club",
    "city": "Broward",
    "state": "FL",
    "address": "Plantation, Broward",
    "phone": "N/A",
    "website": "https://jacarandacountryclub.com/weddings-events/",
    "googleMapsQuery": "Jacaranda Country Club Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Jacaranda%20Country%20Club%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Jacaranda%20Country%20Club%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 23,
    "name": "Deer Creek Country Club",
    "city": "Broward",
    "state": "FL",
    "address": "Deerfield Beach, Broward",
    "phone": "N/A",
    "website": "https://deercreekflorida.com/weddings/",
    "googleMapsQuery": "Deer Creek Country Club Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Deer%20Creek%20Country%20Club%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Deer%20Creek%20Country%20Club%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 24,
    "name": "Bonnet House Museum & Gardens",
    "city": "Broward",
    "state": "FL",
    "address": "Fort Lauderdale, Broward",
    "phone": "N/A",
    "website": "https://www.bonnethouse.org/weddings/",
    "googleMapsQuery": "Bonnet House Museum & Gardens Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Bonnet%20House%20Museum%20%26%20Gardens%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Bonnet%20House%20Museum%20%26%20Gardens%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 25,
    "name": "Stranahan House",
    "city": "Broward",
    "state": "FL",
    "address": "Fort Lauderdale, Broward",
    "phone": "N/A",
    "website": "https://stranahanhouse.org/rentals/",
    "googleMapsQuery": "Stranahan House Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Stranahan%20House%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Stranahan%20House%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 26,
    "name": "Secret Gardens Miami",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Homestead, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.secretgardensmiami.com/",
    "googleMapsQuery": "Secret Gardens Miami Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Secret%20Gardens%20Miami%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Secret%20Gardens%20Miami%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 27,
    "name": "Villa Woodbine",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coconut Grove, Miami-Dade",
    "phone": "N/A",
    "website": "https://villa-woodbine.com/",
    "googleMapsQuery": "Villa Woodbine Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Villa%20Woodbine%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Villa%20Woodbine%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 28,
    "name": "Lavan Venue",
    "city": "Broward",
    "state": "FL",
    "address": "Hollywood, Broward",
    "phone": "N/A",
    "website": "http://lavanvenue.com/",
    "googleMapsQuery": "Lavan Venue Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Lavan%20Venue%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Lavan%20Venue%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 29,
    "name": "Coral Gables Country Club",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coral Gables, Miami-Dade",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Coral Gables Country Club Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Coral%20Gables%20Country%20Club%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Coral%20Gables%20Country%20Club%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 30,
    "name": "Weston Hills Country Club",
    "city": "Broward",
    "state": "FL",
    "address": "Weston, Broward",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Weston Hills Country Club Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Weston%20Hills%20Country%20Club%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Weston%20Hills%20Country%20Club%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 31,
    "name": "Parkland Country Club",
    "city": "Broward",
    "state": "FL",
    "address": "Parkland, Broward",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Parkland Country Club Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Parkland%20Country%20Club%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Parkland%20Country%20Club%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 32,
    "name": "Miami Beach Botanical Garden",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Miami Beach Botanical Garden Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Miami%20Beach%20Botanical%20Garden%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Miami%20Beach%20Botanical%20Garden%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 33,
    "name": "Hollywood's ArtsPark",
    "city": "Broward",
    "state": "FL",
    "address": "Hollywood, Broward",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Hollywood's ArtsPark Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hollywood's%20ArtsPark%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hollywood's%20ArtsPark%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 34,
    "name": "Phillip and Patricia Frost Science Museum",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami, Miami-Dade",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Phillip and Patricia Frost Science Museum Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Phillip%20and%20Patricia%20Frost%20Science%20Museum%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Phillip%20and%20Patricia%20Frost%20Science%20Museum%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 35,
    "name": "The M Building",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Wynwood, Miami-Dade",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "The M Building Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20M%20Building%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20M%20Building%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 36,
    "name": "The Wharf (Miami/Ft. Lauderdale)",
    "city": "Florida",
    "state": "FL",
    "address": "Miami/Fort Lauderdale",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "The Wharf (Miami/Ft. Lauderdale) Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Wharf%20(Miami%2FFt.%20Lauderdale)%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Wharf%20(Miami%2FFt.%20Lauderdale)%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 37,
    "name": "The Biltmore Hotel",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Coral Gables, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.biltmorehotel.com/weddings/",
    "googleMapsQuery": "The Biltmore Hotel Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Biltmore%20Hotel%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Biltmore%20Hotel%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 38,
    "name": "Miami Marriott Biscayne Bay",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Downtown Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/miabb-miami-marriott-biscayne-bay/events/",
    "googleMapsQuery": "Miami Marriott Biscayne Bay Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Miami%20Marriott%20Biscayne%20Bay%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Miami%20Marriott%20Biscayne%20Bay%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 39,
    "name": "Diplomat Beach Resort",
    "city": "Broward",
    "state": "FL",
    "address": "Hollywood, Broward",
    "phone": "N/A",
    "website": "https://www.diplomatresort.com/weddings/",
    "googleMapsQuery": "Diplomat Beach Resort Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Diplomat%20Beach%20Resort%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Diplomat%20Beach%20Resort%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 40,
    "name": "Seminole Hard Rock Hotel & Casino",
    "city": "Broward",
    "state": "FL",
    "address": "Hollywood, Broward",
    "phone": "N/A",
    "website": "https://www.seminolehardrockhollywood.com/meetings-events",
    "googleMapsQuery": "Seminole Hard Rock Hotel & Casino Broward FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Seminole%20Hard%20Rock%20Hotel%20%26%20Casino%20Broward%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Seminole%20Hard%20Rock%20Hotel%20%26%20Casino%20Broward%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 41,
    "name": "Milander Center for Arts & Entertainment",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Hialeah, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.hialeahfl.gov/1029/Milander-Center",
    "googleMapsQuery": "Milander Center for Arts & Entertainment Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Milander%20Center%20for%20Arts%20%26%20Entertainment%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Milander%20Center%20for%20Arts%20%26%20Entertainment%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 42,
    "name": "Pérez Art Museum Miami (PAMM)",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Downtown Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.pamm.org/entertaining",
    "googleMapsQuery": "Pérez Art Museum Miami (PAMM) Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/P%C3%A9rez%20Art%20Museum%20Miami%20(PAMM)%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=P%C3%A9rez%20Art%20Museum%20Miami%20(PAMM)%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 43,
    "name": "JW Marriott Turnberry Resort & Spa",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Aventura, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/miajt-jw-marriott-miami-turnberry-resort-and-spa/events/",
    "googleMapsQuery": "JW Marriott Turnberry Resort & Spa Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/JW%20Marriott%20Turnberry%20Resort%20%26%20Spa%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=JW%20Marriott%20Turnberry%20Resort%20%26%20Spa%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 44,
    "name": "Loews Miami Beach Hotel",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "South Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.loewshotels.com/miami-beach/weddings",
    "googleMapsQuery": "Loews Miami Beach Hotel Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Loews%20Miami%20Beach%20Hotel%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Loews%20Miami%20Beach%20Hotel%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 45,
    "name": "Faena Hotel Miami Beach",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami Beach, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.faena.com/miami-beach/gatherings/weddings",
    "googleMapsQuery": "Faena Hotel Miami Beach Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Faena%20Hotel%20Miami%20Beach%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Faena%20Hotel%20Miami%20Beach%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 46,
    "name": "Eau Palm Beach Resort & Spa",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Manalapan, Palm Beach",
    "phone": "N/A",
    "website": "https://www.eaupalmbeach.com/",
    "googleMapsQuery": "Eau Palm Beach Resort & Spa Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Eau%20Palm%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Eau%20Palm%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 47,
    "name": "Palm Beach Marriott Singer Island Beach Resort & Spa",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Riviera Beach, Palm Beach",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/pbisi-palm-beach-marriott-singer-island-beach-resort-and-spa/events/",
    "googleMapsQuery": "Palm Beach Marriott Singer Island Beach Resort & Spa Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Palm%20Beach%20Marriott%20Singer%20Island%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Palm%20Beach%20Marriott%20Singer%20Island%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 48,
    "name": "The Addison",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Boca Raton, Palm Beach",
    "phone": "N/A",
    "website": "https://theaddison.com/",
    "googleMapsQuery": "The Addison Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Addison%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Addison%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 49,
    "name": "Lady Jean Ranch",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Jupiter, Palm Beach",
    "phone": "N/A",
    "website": "https://www.ladyjeanranch.com/",
    "googleMapsQuery": "Lady Jean Ranch Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Lady%20Jean%20Ranch%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Lady%20Jean%20Ranch%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 50,
    "name": "Out of the Blue Celebrations",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Jupiter, Palm Beach",
    "phone": "N/A",
    "website": "https://www.outofthebluecelebrations.com/",
    "googleMapsQuery": "Out of the Blue Celebrations Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Out%20of%20the%20Blue%20Celebrations%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Out%20of%20the%20Blue%20Celebrations%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 51,
    "name": "The Ben, Autograph Collection",
    "city": "Palm Beach",
    "state": "FL",
    "address": "West Palm Beach, Palm Beach",
    "phone": "N/A",
    "website": "https://www.thebenwestpalm.com/weddings/",
    "googleMapsQuery": "The Ben, Autograph Collection Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Ben%2C%20Autograph%20Collection%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Ben%2C%20Autograph%20Collection%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 52,
    "name": "Tideline Ocean Resort & Spa",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Palm Beach, Palm Beach",
    "phone": "N/A",
    "website": "https://www.tidelineresort.com/",
    "googleMapsQuery": "Tideline Ocean Resort & Spa Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Tideline%20Ocean%20Resort%20%26%20Spa%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Tideline%20Ocean%20Resort%20%26%20Spa%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 53,
    "name": "PGA National Resort",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Palm Beach Gardens, Palm Beach",
    "phone": "N/A",
    "website": "https://www.pgaresort.com/weddings/",
    "googleMapsQuery": "PGA National Resort Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/PGA%20National%20Resort%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=PGA%20National%20Resort%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 54,
    "name": "Pelican Club",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Jupiter, Palm Beach",
    "phone": "N/A",
    "website": "https://www.pelicanclubjupiter.com/",
    "googleMapsQuery": "Pelican Club Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Pelican%20Club%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Pelican%20Club%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 55,
    "name": "The Wanderers Club",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Wellington, Palm Beach",
    "phone": "N/A",
    "website": "https://www.wanderersclubwellington.com/weddings",
    "googleMapsQuery": "The Wanderers Club Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Wanderers%20Club%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Wanderers%20Club%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 56,
    "name": "The Seagate Hotel & Spa",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Delray Beach, Palm Beach",
    "phone": "N/A",
    "website": "https://www.seagatedelray.com/weddings/",
    "googleMapsQuery": "The Seagate Hotel & Spa Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Seagate%20Hotel%20%26%20Spa%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Seagate%20Hotel%20%26%20Spa%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 57,
    "name": "Boca Lago Country Club",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Boca Raton, Palm Beach",
    "phone": "N/A",
    "website": "https://www.bocalago.com/weddings",
    "googleMapsQuery": "Boca Lago Country Club Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Boca%20Lago%20Country%20Club%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Boca%20Lago%20Country%20Club%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 58,
    "name": "The Club at Ibis",
    "city": "Palm Beach",
    "state": "FL",
    "address": "West Palm Beach, Palm Beach",
    "phone": "N/A",
    "website": "https://www.clubatibis.com/",
    "googleMapsQuery": "The Club at Ibis Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Club%20at%20Ibis%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Club%20at%20Ibis%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 59,
    "name": "Canopy by Hilton West Palm Beach",
    "city": "Palm Beach",
    "state": "FL",
    "address": "West Palm Beach, Palm Beach",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Canopy by Hilton West Palm Beach Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Canopy%20by%20Hilton%20West%20Palm%20Beach%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Canopy%20by%20Hilton%20West%20Palm%20Beach%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 60,
    "name": "Jupiter Beach Resort & Spa",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Jupiter, Palm Beach",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Jupiter Beach Resort & Spa Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Jupiter%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Jupiter%20Beach%20Resort%20%26%20Spa%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 61,
    "name": "Loggerhead Marinelife Center",
    "city": "Florida",
    "state": "FL",
    "address": "Palm Beach County",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Loggerhead Marinelife Center Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Loggerhead%20Marinelife%20Center%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Loggerhead%20Marinelife%20Center%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 62,
    "name": "Morikami Museum & Gardens",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Delray Beach, Palm Beach",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Morikami Museum & Gardens Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Morikami%20Museum%20%26%20Gardens%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Morikami%20Museum%20%26%20Gardens%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 63,
    "name": "Sundy House",
    "city": "Palm Beach",
    "state": "FL",
    "address": "Delray Beach, Palm Beach",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Sundy House Palm Beach FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sundy%20House%20Palm%20Beach%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sundy%20House%20Palm%20Beach%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 64,
    "name": "LaPlaya Beach & Golf Resort",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.laplayaresort.com/weddings",
    "googleMapsQuery": "LaPlaya Beach & Golf Resort Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/LaPlaya%20Beach%20%26%20Golf%20Resort%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=LaPlaya%20Beach%20%26%20Golf%20Resort%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 65,
    "name": "Naples Bay Resort & Marina",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.naplesbayresort.com/",
    "googleMapsQuery": "Naples Bay Resort & Marina Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Naples%20Bay%20Resort%20%26%20Marina%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Naples%20Bay%20Resort%20%26%20Marina%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 66,
    "name": "Vineyards Country Club",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "https://vineyardscountryclubnaples.com/",
    "googleMapsQuery": "Vineyards Country Club Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Vineyards%20Country%20Club%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Vineyards%20Country%20Club%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 67,
    "name": "Tiburón Golf Club",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.tiburonnaples.com/",
    "googleMapsQuery": "Tiburón Golf Club Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Tibur%C3%B3n%20Golf%20Club%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Tibur%C3%B3n%20Golf%20Club%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 68,
    "name": "JW Marriott Marco Island Beach Resort",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Marco Island, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/mrkfl-jw-marriott-marco-island-beach-resort/events/",
    "googleMapsQuery": "JW Marriott Marco Island Beach Resort Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/JW%20Marriott%20Marco%20Island%20Beach%20Resort%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=JW%20Marriott%20Marco%20Island%20Beach%20Resort%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 69,
    "name": "Hyatt Regency Coconut Point Resort & Spa",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Bonita Springs, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.hyatt.com/en-US/hotel/florida/hyatt-regency-coconut-point-resort-and-spa/naprn/special-events/weddings",
    "googleMapsQuery": "Hyatt Regency Coconut Point Resort & Spa Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hyatt%20Regency%20Coconut%20Point%20Resort%20%26%20Spa%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hyatt%20Regency%20Coconut%20Point%20Resort%20%26%20Spa%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 70,
    "name": "Sale e Pepe at Marco Beach Ocean Resort",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Marco Island, Southwest Florida",
    "phone": "N/A",
    "website": "https://sale-e-pepe.com/",
    "googleMapsQuery": "Sale e Pepe at Marco Beach Ocean Resort Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sale%20e%20Pepe%20at%20Marco%20Beach%20Ocean%20Resort%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sale%20e%20Pepe%20at%20Marco%20Beach%20Ocean%20Resort%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 71,
    "name": "Pink Shell Beach Resort & Marina",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Fort Myers Beach, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.pinkshell.com/weddings",
    "googleMapsQuery": "Pink Shell Beach Resort & Marina Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Pink%20Shell%20Beach%20Resort%20%26%20Marina%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Pink%20Shell%20Beach%20Resort%20%26%20Marina%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 72,
    "name": "Sundial Beach Resort & Spa",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Sanibel Island, Southwest Florida",
    "phone": "N/A",
    "website": "https://sundialresort.com/weddings/",
    "googleMapsQuery": "Sundial Beach Resort & Spa Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sundial%20Beach%20Resort%20%26%20Spa%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sundial%20Beach%20Resort%20%26%20Spa%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 73,
    "name": "Sanibel Harbour Marriott Resort & Spa",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Fort Myers, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/rswfs-sanibel-harbour-resort-and-spa/events/",
    "googleMapsQuery": "Sanibel Harbour Marriott Resort & Spa Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sanibel%20Harbour%20Marriott%20Resort%20%26%20Spa%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sanibel%20Harbour%20Marriott%20Resort%20%26%20Spa%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 74,
    "name": "Westin Cape Coral Resort at Marina Village",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Cape Coral, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.marriott.com/en-us/hotels/rswwc-the-westin-cape-coral-resort-at-marina-village/events/",
    "googleMapsQuery": "Westin Cape Coral Resort at Marina Village Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Westin%20Cape%20Coral%20Resort%20at%20Marina%20Village%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Westin%20Cape%20Coral%20Resort%20at%20Marina%20Village%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 75,
    "name": "South Seas Island Resort",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Captiva Island, Southwest Florida",
    "phone": "N/A",
    "website": "https://www.southseas.com/weddings",
    "googleMapsQuery": "South Seas Island Resort Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/South%20Seas%20Island%20Resort%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=South%20Seas%20Island%20Resort%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 76,
    "name": "The Club at Grandezza",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Estero, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "The Club at Grandezza Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Club%20at%20Grandezza%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Club%20at%20Grandezza%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 77,
    "name": "The Colony Golf & Country Club",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Bonita Springs, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "The Colony Golf & Country Club Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Colony%20Golf%20%26%20Country%20Club%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Colony%20Golf%20%26%20Country%20Club%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 78,
    "name": "Heritage Bay Golf & Country Club",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Heritage Bay Golf & Country Club Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Heritage%20Bay%20Golf%20%26%20Country%20Club%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Heritage%20Bay%20Golf%20%26%20Country%20Club%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 79,
    "name": "Lover's Key Adventure & Events",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Fort Myers Beach, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Lover's Key Adventure & Events Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Lover's%20Key%20Adventure%20%26%20Events%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Lover's%20Key%20Adventure%20%26%20Events%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 80,
    "name": "Corkscrew Sanctuary",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Corkscrew Sanctuary Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Corkscrew%20Sanctuary%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Corkscrew%20Sanctuary%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 81,
    "name": "Margaritaville Beach Resort",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Fort Myers Beach, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Margaritaville Beach Resort Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Margaritaville%20Beach%20Resort%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Margaritaville%20Beach%20Resort%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 82,
    "name": "Misty Morning Barn",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Fort Myers, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Misty Morning Barn Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Misty%20Morning%20Barn%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Misty%20Morning%20Barn%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 83,
    "name": "Naples Princess",
    "city": "Southwest Florida",
    "state": "FL",
    "address": "Naples, Southwest Florida",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Naples Princess Southwest Florida FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Naples%20Princess%20Southwest%20Florida%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Naples%20Princess%20Southwest%20Florida%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 84,
    "name": "Baker's Cay Resort Key Largo",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key Largo, Florida Keys",
    "phone": "N/A",
    "website": "https://www.bakerscay.com/weddings/",
    "googleMapsQuery": "Baker's Cay Resort Key Largo Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Baker's%20Cay%20Resort%20Key%20Largo%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Baker's%20Cay%20Resort%20Key%20Largo%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 85,
    "name": "Playa Largo Resort & Spa",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key Largo, Florida Keys",
    "phone": "N/A",
    "website": "https://www.playalargoresort.com/weddings/",
    "googleMapsQuery": "Playa Largo Resort & Spa Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Playa%20Largo%20Resort%20%26%20Spa%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Playa%20Largo%20Resort%20%26%20Spa%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 86,
    "name": "Largo Resort",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key Largo, Florida Keys",
    "phone": "N/A",
    "website": "https://www.largoresort.com/",
    "googleMapsQuery": "Largo Resort Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Largo%20Resort%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Largo%20Resort%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 87,
    "name": "Dolphin Point Villas",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key Largo, Florida Keys",
    "phone": "N/A",
    "website": "https://dolphinpointvillas.com/",
    "googleMapsQuery": "Dolphin Point Villas Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Dolphin%20Point%20Villas%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Dolphin%20Point%20Villas%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 88,
    "name": "Islander Resort",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.islanderfloridakeys.com/weddings",
    "googleMapsQuery": "Islander Resort Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Islander%20Resort%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Islander%20Resort%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 89,
    "name": "Cheeca Lodge & Spa",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.cheeca.com/weddings/",
    "googleMapsQuery": "Cheeca Lodge & Spa Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Cheeca%20Lodge%20%26%20Spa%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Cheeca%20Lodge%20%26%20Spa%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 90,
    "name": "Ocean Oasis",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.islamoradabeachhouse.com/",
    "googleMapsQuery": "Ocean Oasis Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Ocean%20Oasis%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Ocean%20Oasis%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 91,
    "name": "Three Waters",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.islamoradaresortcollection.com/weddings",
    "googleMapsQuery": "Three Waters Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Three%20Waters%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Three%20Waters%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 92,
    "name": "La Siesta Resort & Villas",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.islamoradaresortcollection.com/la-siesta-resort-villas",
    "googleMapsQuery": "La Siesta Resort & Villas Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/La%20Siesta%20Resort%20%26%20Villas%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=La%20Siesta%20Resort%20%26%20Villas%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 93,
    "name": "Bud N' Mary's Marina 'The Barn'",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Islamorada, Florida Keys",
    "phone": "N/A",
    "website": "https://www.budnmarys.com/",
    "googleMapsQuery": "Bud N' Mary's Marina 'The Barn' Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Bud%20N'%20Mary's%20Marina%20'The%20Barn'%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Bud%20N'%20Mary's%20Marina%20'The%20Barn'%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 94,
    "name": "Faro Blanco Resort & Yacht Club",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Marathon, Florida Keys",
    "phone": "N/A",
    "website": "https://www.faroblancoresort.com/weddings.htm",
    "googleMapsQuery": "Faro Blanco Resort & Yacht Club Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Faro%20Blanco%20Resort%20%26%20Yacht%20Club%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Faro%20Blanco%20Resort%20%26%20Yacht%20Club%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 95,
    "name": "Isla Bella Beach Resort",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Marathon, Florida Keys",
    "phone": "N/A",
    "website": "https://www.islabellabeachresort.com/weddings/",
    "googleMapsQuery": "Isla Bella Beach Resort Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Isla%20Bella%20Beach%20Resort%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Isla%20Bella%20Beach%20Resort%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 96,
    "name": "East Sister Rock Island",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Marathon, Florida Keys",
    "phone": "N/A",
    "website": "https://floridaisland.com/en/east-sister-rock",
    "googleMapsQuery": "East Sister Rock Island Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/East%20Sister%20Rock%20Island%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=East%20Sister%20Rock%20Island%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 97,
    "name": "Hawks Cay Resort",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Duck Key, Florida Keys",
    "phone": "N/A",
    "website": "https://www.hawkscay.com/weddings",
    "googleMapsQuery": "Hawks Cay Resort Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hawks%20Cay%20Resort%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hawks%20Cay%20Resort%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 98,
    "name": "Margaritaville Beach House Key West",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.margaritavillebeachhousekeywest.com/",
    "googleMapsQuery": "Margaritaville Beach House Key West Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Margaritaville%20Beach%20House%20Key%20West%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Margaritaville%20Beach%20House%20Key%20West%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 99,
    "name": "Audubon House & Tropical Gardens",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.audubonhouse.com/weddings",
    "googleMapsQuery": "Audubon House & Tropical Gardens Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Audubon%20House%20%26%20Tropical%20Gardens%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Audubon%20House%20%26%20Tropical%20Gardens%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 100,
    "name": "The Reach Key West, Curio Collection by Hilton",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.hilton.com/en/hotels/eywthqq-the-reach-key-west/events/",
    "googleMapsQuery": "The Reach Key West, Curio Collection by Hilton Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Reach%20Key%20West%2C%20Curio%20Collection%20by%20Hilton%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Reach%20Key%20West%2C%20Curio%20Collection%20by%20Hilton%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 101,
    "name": "Southernmost Beach Resort",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.southernmostbeachresort.com/weddings",
    "googleMapsQuery": "Southernmost Beach Resort Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Southernmost%20Beach%20Resort%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Southernmost%20Beach%20Resort%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 102,
    "name": "Havana Cabana at Key West",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.havanacabanakeywesthotel.com/",
    "googleMapsQuery": "Havana Cabana at Key West Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Havana%20Cabana%20at%20Key%20West%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Havana%20Cabana%20at%20Key%20West%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 103,
    "name": "Casa Marina Key West, Curio Collection by Hilton",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.casamarinaresort.com/weddings/",
    "googleMapsQuery": "Casa Marina Key West, Curio Collection by Hilton Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Casa%20Marina%20Key%20West%2C%20Curio%20Collection%20by%20Hilton%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Casa%20Marina%20Key%20West%2C%20Curio%20Collection%20by%20Hilton%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 104,
    "name": "Hyatt Centric Key West Resort & Spa",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.hyatt.com/hyatt-centric/en-US/keywh-hyatt-centric-key-west-resort-and-spa/special-events/weddings",
    "googleMapsQuery": "Hyatt Centric Key West Resort & Spa Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hyatt%20Centric%20Key%20West%20Resort%20%26%20Spa%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hyatt%20Centric%20Key%20West%20Resort%20%26%20Spa%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 105,
    "name": "The Perry Hotel & Marina Key West",
    "city": "Key West",
    "state": "Florida",
    "address": "Stock Island, Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.perrykeywest.com/key-west-weddings/",
    "googleMapsQuery": "The Perry Hotel & Marina Key West Key West Florida",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Perry%20Hotel%20%26%20Marina%20Key%20West%20Key%20West%20Florida",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Perry%20Hotel%20%26%20Marina%20Key%20West%20Key%20West%20Florida%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 106,
    "name": "Oceans Edge Resort & Marina",
    "city": "Key West",
    "state": "Florida",
    "address": "Stock Island, Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.oceansedgekeywest.com/weddings/",
    "googleMapsQuery": "Oceans Edge Resort & Marina Key West Florida",
    "googleMapsUrl": "https://www.google.com/maps/search/Oceans%20Edge%20Resort%20%26%20Marina%20Key%20West%20Florida",
    "businessSearchUrl": "https://www.google.com/search?q=Oceans%20Edge%20Resort%20%26%20Marina%20Key%20West%20Florida%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 107,
    "name": "The Garden at the Oldest House Museum",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.oldesthousekeywest.com/",
    "googleMapsQuery": "The Garden at the Oldest House Museum Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Garden%20at%20the%20Oldest%20House%20Museum%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Garden%20at%20the%20Oldest%20House%20Museum%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 108,
    "name": "Sunset Watersports",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://sunsetwatersportskeywest.com/key-west-weddings/",
    "googleMapsQuery": "Sunset Watersports Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sunset%20Watersports%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sunset%20Watersports%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 109,
    "name": "Key West Lighthouse & Keeper's Quarters",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.kwahs.org/properties/lighthouse",
    "googleMapsQuery": "Key West Lighthouse & Keeper's Quarters Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Key%20West%20Lighthouse%20%26%20Keeper's%20Quarters%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Key%20West%20Lighthouse%20%26%20Keeper's%20Quarters%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 110,
    "name": "Fort East Martello",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.kwahs.org/properties/fort-east-martello",
    "googleMapsQuery": "Fort East Martello Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Fort%20East%20Martello%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Fort%20East%20Martello%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 111,
    "name": "Ocean Key Resort & Spa",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.oceankey.com/key-west-weddings",
    "googleMapsQuery": "Ocean Key Resort & Spa Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Ocean%20Key%20Resort%20%26%20Spa%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Ocean%20Key%20Resort%20%26%20Spa%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 112,
    "name": "Old Town Manor",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.oldtownmanor.com/key-west-weddings/",
    "googleMapsQuery": "Old Town Manor Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Old%20Town%20Manor%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Old%20Town%20Manor%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 113,
    "name": "Hard Rock Café Key West",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.hardrockcafe.com/location/key-west/",
    "googleMapsQuery": "Hard Rock Café Key West Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Hard%20Rock%20Caf%C3%A9%20Key%20West%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Hard%20Rock%20Caf%C3%A9%20Key%20West%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 114,
    "name": "Pier House Resort & Spa",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.pierhouse.com/weddings",
    "googleMapsQuery": "Pier House Resort & Spa Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Pier%20House%20Resort%20%26%20Spa%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Pier%20House%20Resort%20%26%20Spa%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 115,
    "name": "Sunset Key Cottages",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.sunsetkeycottages.com/key-west-weddings/",
    "googleMapsQuery": "Sunset Key Cottages Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Sunset%20Key%20Cottages%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Sunset%20Key%20Cottages%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 116,
    "name": "First Flight Island Brewery",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.firstflightkw.com/",
    "googleMapsQuery": "First Flight Island Brewery Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/First%20Flight%20Island%20Brewery%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=First%20Flight%20Island%20Brewery%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 117,
    "name": "Ernest Hemingway Home & Museum",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.hemingwayhome.com/weddings/",
    "googleMapsQuery": "Ernest Hemingway Home & Museum Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Ernest%20Hemingway%20Home%20%26%20Museum%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Ernest%20Hemingway%20Home%20%26%20Museum%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 118,
    "name": "Fort Zachary Taylor State Park",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "https://www.floridastateparks.org/parks-and-trails/fort-zachary-taylor-historic-state-park",
    "googleMapsQuery": "Fort Zachary Taylor State Park Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Fort%20Zachary%20Taylor%20State%20Park%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Fort%20Zachary%20Taylor%20State%20Park%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 119,
    "name": "Bagatelle Restaurant",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Bagatelle Restaurant Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Bagatelle%20Restaurant%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Bagatelle%20Restaurant%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 120,
    "name": "Key West Historic Inns",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Key West Historic Inns Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Key%20West%20Historic%20Inns%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Key%20West%20Historic%20Inns%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 121,
    "name": "The Blue Room",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "The Blue Room Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/The%20Blue%20Room%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=The%20Blue%20Room%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 122,
    "name": "Schooner Appledore",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Schooner Appledore Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Schooner%20Appledore%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Schooner%20Appledore%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 123,
    "name": "Suite Dreams Inn",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Key West, Florida Keys",
    "phone": "N/A",
    "website": "N/A",
    "googleMapsQuery": "Suite Dreams Inn Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Suite%20Dreams%20Inn%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Suite%20Dreams%20Inn%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 124,
    "name": "Patch of Heaven Sanctuary",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Homestead, Miami-Dade",
    "phone": "N/A",
    "website": "https://patchofheavensanctuary.com/",
    "googleMapsQuery": "Patch of Heaven Sanctuary Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Patch%20of%20Heaven%20Sanctuary%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Patch%20of%20Heaven%20Sanctuary%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 125,
    "name": "Redland Koi Gardens",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Redland, Miami-Dade",
    "phone": "N/A",
    "website": "https://redlandkoigardens.com/",
    "googleMapsQuery": "Redland Koi Gardens Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Redland%20Koi%20Gardens%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Redland%20Koi%20Gardens%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 126,
    "name": "Schnebly Redland Winery",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Homestead, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.schneblyredlandswinery.com/",
    "googleMapsQuery": "Schnebly Redland Winery Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Schnebly%20Redland%20Winery%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Schnebly%20Redland%20Winery%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 127,
    "name": "Ever After Farms Tropical Grove Barn",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Homestead, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.everafterfarms.com/tropical-grove-barn/",
    "googleMapsQuery": "Ever After Farms Tropical Grove Barn Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Ever%20After%20Farms%20Tropical%20Grove%20Barn%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Ever%20After%20Farms%20Tropical%20Grove%20Barn%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 128,
    "name": "Villa Toscana Miami",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.vtmiami.com/weddings",
    "googleMapsQuery": "Villa Toscana Miami Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Villa%20Toscana%20Miami%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Villa%20Toscana%20Miami%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 129,
    "name": "East Sister Rock Island",
    "city": "Florida Keys",
    "state": "FL",
    "address": "Marathon, Florida Keys",
    "phone": "N/A",
    "website": "https://floridaisland.com/en/groups-events",
    "googleMapsQuery": "East Sister Rock Island Florida Keys FL",
    "googleMapsUrl": "https://www.google.com/maps/search/East%20Sister%20Rock%20Island%20Florida%20Keys%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=East%20Sister%20Rock%20Island%20Florida%20Keys%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  },
  {
    "id": 130,
    "name": "Jungle Island",
    "city": "Miami-Dade",
    "state": "FL",
    "address": "Miami, Miami-Dade",
    "phone": "N/A",
    "website": "https://www.jungleisland.com/private-events/",
    "googleMapsQuery": "Jungle Island Miami-Dade FL",
    "googleMapsUrl": "https://www.google.com/maps/search/Jungle%20Island%20Miami-Dade%20FL",
    "businessSearchUrl": "https://www.google.com/search?q=Jungle%20Island%20Miami-Dade%20FL%20permanently%20closed%20OR%20temporarily%20closed%20OR%20hours%20OR%20phone"
  }
];

console.log('GOOGLE MAPS VENUE CLOSURE VERIFICATION');
console.log('Total venues to check: ' + venues.length);
console.log('=' * 50);

// Function to check individual venue
function checkVenue(venueIndex) {
  if (venueIndex >= venues.length) {
    console.log('\nAll venues checked!');
    return;
  }
  
  const venue = venues[venueIndex];
  console.log(`\n[${venue.id}/${venues.length}] ${venue.name}`);
  console.log(`City: ${venue.city}, ${venue.state}`);
  console.log(`Google Maps: ${venue.googleMapsUrl}`);
  console.log(`Business Search: ${venue.businessSearchUrl}`);
  console.log('Look for: "Permanently closed", "Temporarily closed", "Hours", "Phone number"');
  console.log('-'.repeat(60));
}

// Check all venues
function checkAllVenues() {
  venues.forEach((venue, index) => {
    checkVenue(index);
  });
}

// Export functions for use
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { venues, checkVenue, checkAllVenues };
}

// Auto-run if called directly
if (require.main === module) {
  checkAllVenues();
}
